
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserPlan = {
  free: 'free',
  plus: 'plus',
  pro: 'pro'
} as const

export type UserPlan = (typeof UserPlan)[keyof typeof UserPlan]


export const MarkSchemeStatus = {
  none: 'none',
  pending: 'pending',
  success: 'success',
  failed: 'failed'
} as const

export type MarkSchemeStatus = (typeof MarkSchemeStatus)[keyof typeof MarkSchemeStatus]


export const ReferenceKind = {
  question_paper: 'question_paper',
  mark_scheme: 'mark_scheme',
  examiner_report: 'examiner_report'
} as const

export type ReferenceKind = (typeof ReferenceKind)[keyof typeof ReferenceKind]


export const ReferenceStatus = {
  pending: 'pending',
  processing: 'processing',
  ready: 'ready',
  failed: 'failed'
} as const

export type ReferenceStatus = (typeof ReferenceStatus)[keyof typeof ReferenceStatus]


export const AttemptMode = {
  mock: 'mock',
  study: 'study'
} as const

export type AttemptMode = (typeof AttemptMode)[keyof typeof AttemptMode]


export const AttemptStatus = {
  in_progress: 'in_progress',
  submitted: 'submitted',
  marking: 'marking',
  marked: 'marked',
  failed: 'failed'
} as const

export type AttemptStatus = (typeof AttemptStatus)[keyof typeof AttemptStatus]


export const ExamLevel = {
  a_level: 'a_level',
  as_level: 'as_level'
} as const

export type ExamLevel = (typeof ExamLevel)[keyof typeof ExamLevel]


export const Subject = {
  maths: 'maths',
  biology: 'biology',
  chemistry: 'chemistry',
  economics: 'economics',
  physics: 'physics',
  psychology: 'psychology'
} as const

export type Subject = (typeof Subject)[keyof typeof Subject]


export const ExamBoard = {
  edexcel: 'edexcel',
  aqa: 'aqa',
  ocr: 'ocr'
} as const

export type ExamBoard = (typeof ExamBoard)[keyof typeof ExamBoard]


export const Status = {
  failed: 'failed',
  pending: 'pending',
  success: 'success'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const StripeSubscriptionStatus = {
  incomplete: 'incomplete',
  incomplete_expired: 'incomplete_expired',
  trialing: 'trialing',
  active: 'active',
  past_due: 'past_due',
  canceled: 'canceled',
  unpaid: 'unpaid',
  paused: 'paused'
} as const

export type StripeSubscriptionStatus = (typeof StripeSubscriptionStatus)[keyof typeof StripeSubscriptionStatus]
