
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Subject = {
  maths: 'maths',
  biology: 'biology',
  chemistry: 'chemistry',
  economics: 'economics',
  physics: 'physics',
  psychology: 'psychology'
} as const

export type Subject = (typeof Subject)[keyof typeof Subject]


export const ExamBoard = {
  edexcel: 'edexcel',
  aqa: 'aqa',
  ocr: 'ocr'
} as const

export type ExamBoard = (typeof ExamBoard)[keyof typeof ExamBoard]


export const Status = {
  failed: 'failed',
  pending: 'pending',
  success: 'success'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const StripeSubscriptionStatus = {
  incomplete: 'incomplete',
  incomplete_expired: 'incomplete_expired',
  trialing: 'trialing',
  active: 'active',
  past_due: 'past_due',
  canceled: 'canceled',
  unpaid: 'unpaid',
  paused: 'paused'
} as const

export type StripeSubscriptionStatus = (typeof StripeSubscriptionStatus)[keyof typeof StripeSubscriptionStatus]
