
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AttemptAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model AttemptAnswer
 * 
 */
export type AttemptAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$AttemptAnswerPayload>

export type AggregateAttemptAnswer = {
  _count: AttemptAnswerCountAggregateOutputType | null
  _avg: AttemptAnswerAvgAggregateOutputType | null
  _sum: AttemptAnswerSumAggregateOutputType | null
  _min: AttemptAnswerMinAggregateOutputType | null
  _max: AttemptAnswerMaxAggregateOutputType | null
}

export type AttemptAnswerAvgAggregateOutputType = {
  id: number | null
  score: number | null
  max_score: number | null
}

export type AttemptAnswerSumAggregateOutputType = {
  id: number | null
  score: number | null
  max_score: number | null
}

export type AttemptAnswerMinAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  attempt_id: string | null
  question_id: string | null
  answer_text: string | null
  score: number | null
  max_score: number | null
  examiner_note: string | null
  model_answer_snapshot: string | null
  prompt_version: string | null
}

export type AttemptAnswerMaxAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  attempt_id: string | null
  question_id: string | null
  answer_text: string | null
  score: number | null
  max_score: number | null
  examiner_note: string | null
  model_answer_snapshot: string | null
  prompt_version: string | null
}

export type AttemptAnswerCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  attempt_id: number
  question_id: number
  answer_text: number
  score: number
  max_score: number
  examiner_note: number
  model_answer_snapshot: number
  prompt_version: number
  _all: number
}


export type AttemptAnswerAvgAggregateInputType = {
  id?: true
  score?: true
  max_score?: true
}

export type AttemptAnswerSumAggregateInputType = {
  id?: true
  score?: true
  max_score?: true
}

export type AttemptAnswerMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  attempt_id?: true
  question_id?: true
  answer_text?: true
  score?: true
  max_score?: true
  examiner_note?: true
  model_answer_snapshot?: true
  prompt_version?: true
}

export type AttemptAnswerMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  attempt_id?: true
  question_id?: true
  answer_text?: true
  score?: true
  max_score?: true
  examiner_note?: true
  model_answer_snapshot?: true
  prompt_version?: true
}

export type AttemptAnswerCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  attempt_id?: true
  question_id?: true
  answer_text?: true
  score?: true
  max_score?: true
  examiner_note?: true
  model_answer_snapshot?: true
  prompt_version?: true
  _all?: true
}

export type AttemptAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AttemptAnswer to aggregate.
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttemptAnswers to fetch.
   */
  orderBy?: Prisma.AttemptAnswerOrderByWithRelationInput | Prisma.AttemptAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AttemptAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttemptAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttemptAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AttemptAnswers
  **/
  _count?: true | AttemptAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AttemptAnswerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AttemptAnswerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AttemptAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AttemptAnswerMaxAggregateInputType
}

export type GetAttemptAnswerAggregateType<T extends AttemptAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateAttemptAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAttemptAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateAttemptAnswer[P]>
}




export type AttemptAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttemptAnswerWhereInput
  orderBy?: Prisma.AttemptAnswerOrderByWithAggregationInput | Prisma.AttemptAnswerOrderByWithAggregationInput[]
  by: Prisma.AttemptAnswerScalarFieldEnum[] | Prisma.AttemptAnswerScalarFieldEnum
  having?: Prisma.AttemptAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AttemptAnswerCountAggregateInputType | true
  _avg?: AttemptAnswerAvgAggregateInputType
  _sum?: AttemptAnswerSumAggregateInputType
  _min?: AttemptAnswerMinAggregateInputType
  _max?: AttemptAnswerMaxAggregateInputType
}

export type AttemptAnswerGroupByOutputType = {
  id: number
  created_at: Date
  updated_at: Date
  attempt_id: string
  question_id: string
  answer_text: string
  score: number | null
  max_score: number
  examiner_note: string | null
  model_answer_snapshot: string | null
  prompt_version: string | null
  _count: AttemptAnswerCountAggregateOutputType | null
  _avg: AttemptAnswerAvgAggregateOutputType | null
  _sum: AttemptAnswerSumAggregateOutputType | null
  _min: AttemptAnswerMinAggregateOutputType | null
  _max: AttemptAnswerMaxAggregateOutputType | null
}

export type GetAttemptAnswerGroupByPayload<T extends AttemptAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AttemptAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AttemptAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AttemptAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AttemptAnswerGroupByOutputType[P]>
      }
    >
  >



export type AttemptAnswerWhereInput = {
  AND?: Prisma.AttemptAnswerWhereInput | Prisma.AttemptAnswerWhereInput[]
  OR?: Prisma.AttemptAnswerWhereInput[]
  NOT?: Prisma.AttemptAnswerWhereInput | Prisma.AttemptAnswerWhereInput[]
  id?: Prisma.IntFilter<"AttemptAnswer"> | number
  created_at?: Prisma.DateTimeFilter<"AttemptAnswer"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"AttemptAnswer"> | Date | string
  attempt_id?: Prisma.StringFilter<"AttemptAnswer"> | string
  question_id?: Prisma.StringFilter<"AttemptAnswer"> | string
  answer_text?: Prisma.StringFilter<"AttemptAnswer"> | string
  score?: Prisma.IntNullableFilter<"AttemptAnswer"> | number | null
  max_score?: Prisma.IntFilter<"AttemptAnswer"> | number
  examiner_note?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  model_answer_snapshot?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  prompt_version?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  attempt?: Prisma.XOR<Prisma.AttemptScalarRelationFilter, Prisma.AttemptWhereInput>
}

export type AttemptAnswerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  attempt_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  answer_text?: Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  max_score?: Prisma.SortOrder
  examiner_note?: Prisma.SortOrderInput | Prisma.SortOrder
  model_answer_snapshot?: Prisma.SortOrderInput | Prisma.SortOrder
  prompt_version?: Prisma.SortOrderInput | Prisma.SortOrder
  attempt?: Prisma.AttemptOrderByWithRelationInput
}

export type AttemptAnswerWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  attempt_id_question_id?: Prisma.AttemptAnswerAttempt_idQuestion_idCompoundUniqueInput
  AND?: Prisma.AttemptAnswerWhereInput | Prisma.AttemptAnswerWhereInput[]
  OR?: Prisma.AttemptAnswerWhereInput[]
  NOT?: Prisma.AttemptAnswerWhereInput | Prisma.AttemptAnswerWhereInput[]
  created_at?: Prisma.DateTimeFilter<"AttemptAnswer"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"AttemptAnswer"> | Date | string
  attempt_id?: Prisma.StringFilter<"AttemptAnswer"> | string
  question_id?: Prisma.StringFilter<"AttemptAnswer"> | string
  answer_text?: Prisma.StringFilter<"AttemptAnswer"> | string
  score?: Prisma.IntNullableFilter<"AttemptAnswer"> | number | null
  max_score?: Prisma.IntFilter<"AttemptAnswer"> | number
  examiner_note?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  model_answer_snapshot?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  prompt_version?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  attempt?: Prisma.XOR<Prisma.AttemptScalarRelationFilter, Prisma.AttemptWhereInput>
}, "id" | "id" | "attempt_id_question_id">

export type AttemptAnswerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  attempt_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  answer_text?: Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  max_score?: Prisma.SortOrder
  examiner_note?: Prisma.SortOrderInput | Prisma.SortOrder
  model_answer_snapshot?: Prisma.SortOrderInput | Prisma.SortOrder
  prompt_version?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AttemptAnswerCountOrderByAggregateInput
  _avg?: Prisma.AttemptAnswerAvgOrderByAggregateInput
  _max?: Prisma.AttemptAnswerMaxOrderByAggregateInput
  _min?: Prisma.AttemptAnswerMinOrderByAggregateInput
  _sum?: Prisma.AttemptAnswerSumOrderByAggregateInput
}

export type AttemptAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.AttemptAnswerScalarWhereWithAggregatesInput | Prisma.AttemptAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.AttemptAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AttemptAnswerScalarWhereWithAggregatesInput | Prisma.AttemptAnswerScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AttemptAnswer"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"AttemptAnswer"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"AttemptAnswer"> | Date | string
  attempt_id?: Prisma.StringWithAggregatesFilter<"AttemptAnswer"> | string
  question_id?: Prisma.StringWithAggregatesFilter<"AttemptAnswer"> | string
  answer_text?: Prisma.StringWithAggregatesFilter<"AttemptAnswer"> | string
  score?: Prisma.IntNullableWithAggregatesFilter<"AttemptAnswer"> | number | null
  max_score?: Prisma.IntWithAggregatesFilter<"AttemptAnswer"> | number
  examiner_note?: Prisma.StringNullableWithAggregatesFilter<"AttemptAnswer"> | string | null
  model_answer_snapshot?: Prisma.StringNullableWithAggregatesFilter<"AttemptAnswer"> | string | null
  prompt_version?: Prisma.StringNullableWithAggregatesFilter<"AttemptAnswer"> | string | null
}

export type AttemptAnswerCreateInput = {
  created_at?: Date | string
  updated_at?: Date | string
  question_id: string
  answer_text: string
  score?: number | null
  max_score: number
  examiner_note?: string | null
  model_answer_snapshot?: string | null
  prompt_version?: string | null
  attempt: Prisma.AttemptCreateNestedOneWithoutAnswersInput
}

export type AttemptAnswerUncheckedCreateInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  attempt_id: string
  question_id: string
  answer_text: string
  score?: number | null
  max_score: number
  examiner_note?: string | null
  model_answer_snapshot?: string | null
  prompt_version?: string | null
}

export type AttemptAnswerUpdateInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attempt?: Prisma.AttemptUpdateOneRequiredWithoutAnswersNestedInput
}

export type AttemptAnswerUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attempt_id?: Prisma.StringFieldUpdateOperationsInput | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AttemptAnswerCreateManyInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  attempt_id: string
  question_id: string
  answer_text: string
  score?: number | null
  max_score: number
  examiner_note?: string | null
  model_answer_snapshot?: string | null
  prompt_version?: string | null
}

export type AttemptAnswerUpdateManyMutationInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AttemptAnswerUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attempt_id?: Prisma.StringFieldUpdateOperationsInput | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AttemptAnswerListRelationFilter = {
  every?: Prisma.AttemptAnswerWhereInput
  some?: Prisma.AttemptAnswerWhereInput
  none?: Prisma.AttemptAnswerWhereInput
}

export type AttemptAnswerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AttemptAnswerAttempt_idQuestion_idCompoundUniqueInput = {
  attempt_id: string
  question_id: string
}

export type AttemptAnswerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  attempt_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  answer_text?: Prisma.SortOrder
  score?: Prisma.SortOrder
  max_score?: Prisma.SortOrder
  examiner_note?: Prisma.SortOrder
  model_answer_snapshot?: Prisma.SortOrder
  prompt_version?: Prisma.SortOrder
}

export type AttemptAnswerAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  score?: Prisma.SortOrder
  max_score?: Prisma.SortOrder
}

export type AttemptAnswerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  attempt_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  answer_text?: Prisma.SortOrder
  score?: Prisma.SortOrder
  max_score?: Prisma.SortOrder
  examiner_note?: Prisma.SortOrder
  model_answer_snapshot?: Prisma.SortOrder
  prompt_version?: Prisma.SortOrder
}

export type AttemptAnswerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  attempt_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  answer_text?: Prisma.SortOrder
  score?: Prisma.SortOrder
  max_score?: Prisma.SortOrder
  examiner_note?: Prisma.SortOrder
  model_answer_snapshot?: Prisma.SortOrder
  prompt_version?: Prisma.SortOrder
}

export type AttemptAnswerSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  score?: Prisma.SortOrder
  max_score?: Prisma.SortOrder
}

export type AttemptAnswerCreateNestedManyWithoutAttemptInput = {
  create?: Prisma.XOR<Prisma.AttemptAnswerCreateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput> | Prisma.AttemptAnswerCreateWithoutAttemptInput[] | Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput[]
  connectOrCreate?: Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput | Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput[]
  createMany?: Prisma.AttemptAnswerCreateManyAttemptInputEnvelope
  connect?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
}

export type AttemptAnswerUncheckedCreateNestedManyWithoutAttemptInput = {
  create?: Prisma.XOR<Prisma.AttemptAnswerCreateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput> | Prisma.AttemptAnswerCreateWithoutAttemptInput[] | Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput[]
  connectOrCreate?: Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput | Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput[]
  createMany?: Prisma.AttemptAnswerCreateManyAttemptInputEnvelope
  connect?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
}

export type AttemptAnswerUpdateManyWithoutAttemptNestedInput = {
  create?: Prisma.XOR<Prisma.AttemptAnswerCreateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput> | Prisma.AttemptAnswerCreateWithoutAttemptInput[] | Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput[]
  connectOrCreate?: Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput | Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput[]
  upsert?: Prisma.AttemptAnswerUpsertWithWhereUniqueWithoutAttemptInput | Prisma.AttemptAnswerUpsertWithWhereUniqueWithoutAttemptInput[]
  createMany?: Prisma.AttemptAnswerCreateManyAttemptInputEnvelope
  set?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  disconnect?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  delete?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  connect?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  update?: Prisma.AttemptAnswerUpdateWithWhereUniqueWithoutAttemptInput | Prisma.AttemptAnswerUpdateWithWhereUniqueWithoutAttemptInput[]
  updateMany?: Prisma.AttemptAnswerUpdateManyWithWhereWithoutAttemptInput | Prisma.AttemptAnswerUpdateManyWithWhereWithoutAttemptInput[]
  deleteMany?: Prisma.AttemptAnswerScalarWhereInput | Prisma.AttemptAnswerScalarWhereInput[]
}

export type AttemptAnswerUncheckedUpdateManyWithoutAttemptNestedInput = {
  create?: Prisma.XOR<Prisma.AttemptAnswerCreateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput> | Prisma.AttemptAnswerCreateWithoutAttemptInput[] | Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput[]
  connectOrCreate?: Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput | Prisma.AttemptAnswerCreateOrConnectWithoutAttemptInput[]
  upsert?: Prisma.AttemptAnswerUpsertWithWhereUniqueWithoutAttemptInput | Prisma.AttemptAnswerUpsertWithWhereUniqueWithoutAttemptInput[]
  createMany?: Prisma.AttemptAnswerCreateManyAttemptInputEnvelope
  set?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  disconnect?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  delete?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  connect?: Prisma.AttemptAnswerWhereUniqueInput | Prisma.AttemptAnswerWhereUniqueInput[]
  update?: Prisma.AttemptAnswerUpdateWithWhereUniqueWithoutAttemptInput | Prisma.AttemptAnswerUpdateWithWhereUniqueWithoutAttemptInput[]
  updateMany?: Prisma.AttemptAnswerUpdateManyWithWhereWithoutAttemptInput | Prisma.AttemptAnswerUpdateManyWithWhereWithoutAttemptInput[]
  deleteMany?: Prisma.AttemptAnswerScalarWhereInput | Prisma.AttemptAnswerScalarWhereInput[]
}

export type AttemptAnswerCreateWithoutAttemptInput = {
  created_at?: Date | string
  updated_at?: Date | string
  question_id: string
  answer_text: string
  score?: number | null
  max_score: number
  examiner_note?: string | null
  model_answer_snapshot?: string | null
  prompt_version?: string | null
}

export type AttemptAnswerUncheckedCreateWithoutAttemptInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  question_id: string
  answer_text: string
  score?: number | null
  max_score: number
  examiner_note?: string | null
  model_answer_snapshot?: string | null
  prompt_version?: string | null
}

export type AttemptAnswerCreateOrConnectWithoutAttemptInput = {
  where: Prisma.AttemptAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.AttemptAnswerCreateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput>
}

export type AttemptAnswerCreateManyAttemptInputEnvelope = {
  data: Prisma.AttemptAnswerCreateManyAttemptInput | Prisma.AttemptAnswerCreateManyAttemptInput[]
  skipDuplicates?: boolean
}

export type AttemptAnswerUpsertWithWhereUniqueWithoutAttemptInput = {
  where: Prisma.AttemptAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.AttemptAnswerUpdateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedUpdateWithoutAttemptInput>
  create: Prisma.XOR<Prisma.AttemptAnswerCreateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedCreateWithoutAttemptInput>
}

export type AttemptAnswerUpdateWithWhereUniqueWithoutAttemptInput = {
  where: Prisma.AttemptAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.AttemptAnswerUpdateWithoutAttemptInput, Prisma.AttemptAnswerUncheckedUpdateWithoutAttemptInput>
}

export type AttemptAnswerUpdateManyWithWhereWithoutAttemptInput = {
  where: Prisma.AttemptAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.AttemptAnswerUpdateManyMutationInput, Prisma.AttemptAnswerUncheckedUpdateManyWithoutAttemptInput>
}

export type AttemptAnswerScalarWhereInput = {
  AND?: Prisma.AttemptAnswerScalarWhereInput | Prisma.AttemptAnswerScalarWhereInput[]
  OR?: Prisma.AttemptAnswerScalarWhereInput[]
  NOT?: Prisma.AttemptAnswerScalarWhereInput | Prisma.AttemptAnswerScalarWhereInput[]
  id?: Prisma.IntFilter<"AttemptAnswer"> | number
  created_at?: Prisma.DateTimeFilter<"AttemptAnswer"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"AttemptAnswer"> | Date | string
  attempt_id?: Prisma.StringFilter<"AttemptAnswer"> | string
  question_id?: Prisma.StringFilter<"AttemptAnswer"> | string
  answer_text?: Prisma.StringFilter<"AttemptAnswer"> | string
  score?: Prisma.IntNullableFilter<"AttemptAnswer"> | number | null
  max_score?: Prisma.IntFilter<"AttemptAnswer"> | number
  examiner_note?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  model_answer_snapshot?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
  prompt_version?: Prisma.StringNullableFilter<"AttemptAnswer"> | string | null
}

export type AttemptAnswerCreateManyAttemptInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  question_id: string
  answer_text: string
  score?: number | null
  max_score: number
  examiner_note?: string | null
  model_answer_snapshot?: string | null
  prompt_version?: string | null
}

export type AttemptAnswerUpdateWithoutAttemptInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AttemptAnswerUncheckedUpdateWithoutAttemptInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AttemptAnswerUncheckedUpdateManyWithoutAttemptInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  answer_text?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_score?: Prisma.IntFieldUpdateOperationsInput | number
  examiner_note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  model_answer_snapshot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AttemptAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  attempt_id?: boolean
  question_id?: boolean
  answer_text?: boolean
  score?: boolean
  max_score?: boolean
  examiner_note?: boolean
  model_answer_snapshot?: boolean
  prompt_version?: boolean
  attempt?: boolean | Prisma.AttemptDefaultArgs<ExtArgs>
}, ExtArgs["result"]["attemptAnswer"]>

export type AttemptAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  attempt_id?: boolean
  question_id?: boolean
  answer_text?: boolean
  score?: boolean
  max_score?: boolean
  examiner_note?: boolean
  model_answer_snapshot?: boolean
  prompt_version?: boolean
  attempt?: boolean | Prisma.AttemptDefaultArgs<ExtArgs>
}, ExtArgs["result"]["attemptAnswer"]>

export type AttemptAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  attempt_id?: boolean
  question_id?: boolean
  answer_text?: boolean
  score?: boolean
  max_score?: boolean
  examiner_note?: boolean
  model_answer_snapshot?: boolean
  prompt_version?: boolean
  attempt?: boolean | Prisma.AttemptDefaultArgs<ExtArgs>
}, ExtArgs["result"]["attemptAnswer"]>

export type AttemptAnswerSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  attempt_id?: boolean
  question_id?: boolean
  answer_text?: boolean
  score?: boolean
  max_score?: boolean
  examiner_note?: boolean
  model_answer_snapshot?: boolean
  prompt_version?: boolean
}

export type AttemptAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "attempt_id" | "question_id" | "answer_text" | "score" | "max_score" | "examiner_note" | "model_answer_snapshot" | "prompt_version", ExtArgs["result"]["attemptAnswer"]>
export type AttemptAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attempt?: boolean | Prisma.AttemptDefaultArgs<ExtArgs>
}
export type AttemptAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attempt?: boolean | Prisma.AttemptDefaultArgs<ExtArgs>
}
export type AttemptAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attempt?: boolean | Prisma.AttemptDefaultArgs<ExtArgs>
}

export type $AttemptAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AttemptAnswer"
  objects: {
    attempt: Prisma.$AttemptPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    created_at: Date
    updated_at: Date
    attempt_id: string
    question_id: string
    answer_text: string
    score: number | null
    max_score: number
    examiner_note: string | null
    model_answer_snapshot: string | null
    prompt_version: string | null
  }, ExtArgs["result"]["attemptAnswer"]>
  composites: {}
}

export type AttemptAnswerGetPayload<S extends boolean | null | undefined | AttemptAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload, S>

export type AttemptAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AttemptAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AttemptAnswerCountAggregateInputType | true
  }

export interface AttemptAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AttemptAnswer'], meta: { name: 'AttemptAnswer' } }
  /**
   * Find zero or one AttemptAnswer that matches the filter.
   * @param {AttemptAnswerFindUniqueArgs} args - Arguments to find a AttemptAnswer
   * @example
   * // Get one AttemptAnswer
   * const attemptAnswer = await prisma.attemptAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AttemptAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, AttemptAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AttemptAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AttemptAnswerFindUniqueOrThrowArgs} args - Arguments to find a AttemptAnswer
   * @example
   * // Get one AttemptAnswer
   * const attemptAnswer = await prisma.attemptAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AttemptAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AttemptAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AttemptAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerFindFirstArgs} args - Arguments to find a AttemptAnswer
   * @example
   * // Get one AttemptAnswer
   * const attemptAnswer = await prisma.attemptAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AttemptAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, AttemptAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AttemptAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerFindFirstOrThrowArgs} args - Arguments to find a AttemptAnswer
   * @example
   * // Get one AttemptAnswer
   * const attemptAnswer = await prisma.attemptAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AttemptAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AttemptAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AttemptAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AttemptAnswers
   * const attemptAnswers = await prisma.attemptAnswer.findMany()
   * 
   * // Get first 10 AttemptAnswers
   * const attemptAnswers = await prisma.attemptAnswer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const attemptAnswerWithIdOnly = await prisma.attemptAnswer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AttemptAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, AttemptAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AttemptAnswer.
   * @param {AttemptAnswerCreateArgs} args - Arguments to create a AttemptAnswer.
   * @example
   * // Create one AttemptAnswer
   * const AttemptAnswer = await prisma.attemptAnswer.create({
   *   data: {
   *     // ... data to create a AttemptAnswer
   *   }
   * })
   * 
   */
  create<T extends AttemptAnswerCreateArgs>(args: Prisma.SelectSubset<T, AttemptAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AttemptAnswers.
   * @param {AttemptAnswerCreateManyArgs} args - Arguments to create many AttemptAnswers.
   * @example
   * // Create many AttemptAnswers
   * const attemptAnswer = await prisma.attemptAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AttemptAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, AttemptAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AttemptAnswers and returns the data saved in the database.
   * @param {AttemptAnswerCreateManyAndReturnArgs} args - Arguments to create many AttemptAnswers.
   * @example
   * // Create many AttemptAnswers
   * const attemptAnswer = await prisma.attemptAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AttemptAnswers and only return the `id`
   * const attemptAnswerWithIdOnly = await prisma.attemptAnswer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AttemptAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AttemptAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AttemptAnswer.
   * @param {AttemptAnswerDeleteArgs} args - Arguments to delete one AttemptAnswer.
   * @example
   * // Delete one AttemptAnswer
   * const AttemptAnswer = await prisma.attemptAnswer.delete({
   *   where: {
   *     // ... filter to delete one AttemptAnswer
   *   }
   * })
   * 
   */
  delete<T extends AttemptAnswerDeleteArgs>(args: Prisma.SelectSubset<T, AttemptAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AttemptAnswer.
   * @param {AttemptAnswerUpdateArgs} args - Arguments to update one AttemptAnswer.
   * @example
   * // Update one AttemptAnswer
   * const attemptAnswer = await prisma.attemptAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AttemptAnswerUpdateArgs>(args: Prisma.SelectSubset<T, AttemptAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AttemptAnswers.
   * @param {AttemptAnswerDeleteManyArgs} args - Arguments to filter AttemptAnswers to delete.
   * @example
   * // Delete a few AttemptAnswers
   * const { count } = await prisma.attemptAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AttemptAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, AttemptAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AttemptAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AttemptAnswers
   * const attemptAnswer = await prisma.attemptAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AttemptAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, AttemptAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AttemptAnswers and returns the data updated in the database.
   * @param {AttemptAnswerUpdateManyAndReturnArgs} args - Arguments to update many AttemptAnswers.
   * @example
   * // Update many AttemptAnswers
   * const attemptAnswer = await prisma.attemptAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AttemptAnswers and only return the `id`
   * const attemptAnswerWithIdOnly = await prisma.attemptAnswer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AttemptAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AttemptAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AttemptAnswer.
   * @param {AttemptAnswerUpsertArgs} args - Arguments to update or create a AttemptAnswer.
   * @example
   * // Update or create a AttemptAnswer
   * const attemptAnswer = await prisma.attemptAnswer.upsert({
   *   create: {
   *     // ... data to create a AttemptAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AttemptAnswer we want to update
   *   }
   * })
   */
  upsert<T extends AttemptAnswerUpsertArgs>(args: Prisma.SelectSubset<T, AttemptAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__AttemptAnswerClient<runtime.Types.Result.GetResult<Prisma.$AttemptAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AttemptAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerCountArgs} args - Arguments to filter AttemptAnswers to count.
   * @example
   * // Count the number of AttemptAnswers
   * const count = await prisma.attemptAnswer.count({
   *   where: {
   *     // ... the filter for the AttemptAnswers we want to count
   *   }
   * })
  **/
  count<T extends AttemptAnswerCountArgs>(
    args?: Prisma.Subset<T, AttemptAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AttemptAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AttemptAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AttemptAnswerAggregateArgs>(args: Prisma.Subset<T, AttemptAnswerAggregateArgs>): Prisma.PrismaPromise<GetAttemptAnswerAggregateType<T>>

  /**
   * Group by AttemptAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttemptAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AttemptAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AttemptAnswerGroupByArgs['orderBy'] }
      : { orderBy?: AttemptAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AttemptAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAttemptAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AttemptAnswer model
 */
readonly fields: AttemptAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AttemptAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AttemptAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  attempt<T extends Prisma.AttemptDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AttemptDefaultArgs<ExtArgs>>): Prisma.Prisma__AttemptClient<runtime.Types.Result.GetResult<Prisma.$AttemptPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AttemptAnswer model
 */
export interface AttemptAnswerFieldRefs {
  readonly id: Prisma.FieldRef<"AttemptAnswer", 'Int'>
  readonly created_at: Prisma.FieldRef<"AttemptAnswer", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"AttemptAnswer", 'DateTime'>
  readonly attempt_id: Prisma.FieldRef<"AttemptAnswer", 'String'>
  readonly question_id: Prisma.FieldRef<"AttemptAnswer", 'String'>
  readonly answer_text: Prisma.FieldRef<"AttemptAnswer", 'String'>
  readonly score: Prisma.FieldRef<"AttemptAnswer", 'Int'>
  readonly max_score: Prisma.FieldRef<"AttemptAnswer", 'Int'>
  readonly examiner_note: Prisma.FieldRef<"AttemptAnswer", 'String'>
  readonly model_answer_snapshot: Prisma.FieldRef<"AttemptAnswer", 'String'>
  readonly prompt_version: Prisma.FieldRef<"AttemptAnswer", 'String'>
}
    

// Custom InputTypes
/**
 * AttemptAnswer findUnique
 */
export type AttemptAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * Filter, which AttemptAnswer to fetch.
   */
  where: Prisma.AttemptAnswerWhereUniqueInput
}

/**
 * AttemptAnswer findUniqueOrThrow
 */
export type AttemptAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * Filter, which AttemptAnswer to fetch.
   */
  where: Prisma.AttemptAnswerWhereUniqueInput
}

/**
 * AttemptAnswer findFirst
 */
export type AttemptAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * Filter, which AttemptAnswer to fetch.
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttemptAnswers to fetch.
   */
  orderBy?: Prisma.AttemptAnswerOrderByWithRelationInput | Prisma.AttemptAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AttemptAnswers.
   */
  cursor?: Prisma.AttemptAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttemptAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttemptAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AttemptAnswers.
   */
  distinct?: Prisma.AttemptAnswerScalarFieldEnum | Prisma.AttemptAnswerScalarFieldEnum[]
}

/**
 * AttemptAnswer findFirstOrThrow
 */
export type AttemptAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * Filter, which AttemptAnswer to fetch.
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttemptAnswers to fetch.
   */
  orderBy?: Prisma.AttemptAnswerOrderByWithRelationInput | Prisma.AttemptAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AttemptAnswers.
   */
  cursor?: Prisma.AttemptAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttemptAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttemptAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AttemptAnswers.
   */
  distinct?: Prisma.AttemptAnswerScalarFieldEnum | Prisma.AttemptAnswerScalarFieldEnum[]
}

/**
 * AttemptAnswer findMany
 */
export type AttemptAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * Filter, which AttemptAnswers to fetch.
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AttemptAnswers to fetch.
   */
  orderBy?: Prisma.AttemptAnswerOrderByWithRelationInput | Prisma.AttemptAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AttemptAnswers.
   */
  cursor?: Prisma.AttemptAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AttemptAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AttemptAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AttemptAnswers.
   */
  distinct?: Prisma.AttemptAnswerScalarFieldEnum | Prisma.AttemptAnswerScalarFieldEnum[]
}

/**
 * AttemptAnswer create
 */
export type AttemptAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a AttemptAnswer.
   */
  data: Prisma.XOR<Prisma.AttemptAnswerCreateInput, Prisma.AttemptAnswerUncheckedCreateInput>
}

/**
 * AttemptAnswer createMany
 */
export type AttemptAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AttemptAnswers.
   */
  data: Prisma.AttemptAnswerCreateManyInput | Prisma.AttemptAnswerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AttemptAnswer createManyAndReturn
 */
export type AttemptAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many AttemptAnswers.
   */
  data: Prisma.AttemptAnswerCreateManyInput | Prisma.AttemptAnswerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AttemptAnswer update
 */
export type AttemptAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a AttemptAnswer.
   */
  data: Prisma.XOR<Prisma.AttemptAnswerUpdateInput, Prisma.AttemptAnswerUncheckedUpdateInput>
  /**
   * Choose, which AttemptAnswer to update.
   */
  where: Prisma.AttemptAnswerWhereUniqueInput
}

/**
 * AttemptAnswer updateMany
 */
export type AttemptAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AttemptAnswers.
   */
  data: Prisma.XOR<Prisma.AttemptAnswerUpdateManyMutationInput, Prisma.AttemptAnswerUncheckedUpdateManyInput>
  /**
   * Filter which AttemptAnswers to update
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * Limit how many AttemptAnswers to update.
   */
  limit?: number
}

/**
 * AttemptAnswer updateManyAndReturn
 */
export type AttemptAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * The data used to update AttemptAnswers.
   */
  data: Prisma.XOR<Prisma.AttemptAnswerUpdateManyMutationInput, Prisma.AttemptAnswerUncheckedUpdateManyInput>
  /**
   * Filter which AttemptAnswers to update
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * Limit how many AttemptAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AttemptAnswer upsert
 */
export type AttemptAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the AttemptAnswer to update in case it exists.
   */
  where: Prisma.AttemptAnswerWhereUniqueInput
  /**
   * In case the AttemptAnswer found by the `where` argument doesn't exist, create a new AttemptAnswer with this data.
   */
  create: Prisma.XOR<Prisma.AttemptAnswerCreateInput, Prisma.AttemptAnswerUncheckedCreateInput>
  /**
   * In case the AttemptAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AttemptAnswerUpdateInput, Prisma.AttemptAnswerUncheckedUpdateInput>
}

/**
 * AttemptAnswer delete
 */
export type AttemptAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
  /**
   * Filter which AttemptAnswer to delete.
   */
  where: Prisma.AttemptAnswerWhereUniqueInput
}

/**
 * AttemptAnswer deleteMany
 */
export type AttemptAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AttemptAnswers to delete
   */
  where?: Prisma.AttemptAnswerWhereInput
  /**
   * Limit how many AttemptAnswers to delete.
   */
  limit?: number
}

/**
 * AttemptAnswer without action
 */
export type AttemptAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttemptAnswer
   */
  select?: Prisma.AttemptAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttemptAnswer
   */
  omit?: Prisma.AttemptAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttemptAnswerInclude<ExtArgs> | null
}
