
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LlmModelConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LlmModelConfig
 * 
 */
export type LlmModelConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$LlmModelConfigPayload>

export type AggregateLlmModelConfig = {
  _count: LlmModelConfigCountAggregateOutputType | null
  _avg: LlmModelConfigAvgAggregateOutputType | null
  _sum: LlmModelConfigSumAggregateOutputType | null
  _min: LlmModelConfigMinAggregateOutputType | null
  _max: LlmModelConfigMaxAggregateOutputType | null
}

export type LlmModelConfigAvgAggregateOutputType = {
  id: number | null
}

export type LlmModelConfigSumAggregateOutputType = {
  id: number | null
}

export type LlmModelConfigMinAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  key: string | null
  model_id: string | null
  provider: string | null
  description: string | null
  is_active: boolean | null
}

export type LlmModelConfigMaxAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  key: string | null
  model_id: string | null
  provider: string | null
  description: string | null
  is_active: boolean | null
}

export type LlmModelConfigCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  key: number
  model_id: number
  provider: number
  description: number
  is_active: number
  _all: number
}


export type LlmModelConfigAvgAggregateInputType = {
  id?: true
}

export type LlmModelConfigSumAggregateInputType = {
  id?: true
}

export type LlmModelConfigMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  key?: true
  model_id?: true
  provider?: true
  description?: true
  is_active?: true
}

export type LlmModelConfigMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  key?: true
  model_id?: true
  provider?: true
  description?: true
  is_active?: true
}

export type LlmModelConfigCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  key?: true
  model_id?: true
  provider?: true
  description?: true
  is_active?: true
  _all?: true
}

export type LlmModelConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LlmModelConfig to aggregate.
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LlmModelConfigs to fetch.
   */
  orderBy?: Prisma.LlmModelConfigOrderByWithRelationInput | Prisma.LlmModelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LlmModelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LlmModelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LlmModelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LlmModelConfigs
  **/
  _count?: true | LlmModelConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LlmModelConfigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LlmModelConfigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LlmModelConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LlmModelConfigMaxAggregateInputType
}

export type GetLlmModelConfigAggregateType<T extends LlmModelConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateLlmModelConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLlmModelConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateLlmModelConfig[P]>
}




export type LlmModelConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LlmModelConfigWhereInput
  orderBy?: Prisma.LlmModelConfigOrderByWithAggregationInput | Prisma.LlmModelConfigOrderByWithAggregationInput[]
  by: Prisma.LlmModelConfigScalarFieldEnum[] | Prisma.LlmModelConfigScalarFieldEnum
  having?: Prisma.LlmModelConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LlmModelConfigCountAggregateInputType | true
  _avg?: LlmModelConfigAvgAggregateInputType
  _sum?: LlmModelConfigSumAggregateInputType
  _min?: LlmModelConfigMinAggregateInputType
  _max?: LlmModelConfigMaxAggregateInputType
}

export type LlmModelConfigGroupByOutputType = {
  id: number
  created_at: Date
  updated_at: Date
  key: string
  model_id: string
  provider: string
  description: string | null
  is_active: boolean
  _count: LlmModelConfigCountAggregateOutputType | null
  _avg: LlmModelConfigAvgAggregateOutputType | null
  _sum: LlmModelConfigSumAggregateOutputType | null
  _min: LlmModelConfigMinAggregateOutputType | null
  _max: LlmModelConfigMaxAggregateOutputType | null
}

export type GetLlmModelConfigGroupByPayload<T extends LlmModelConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LlmModelConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LlmModelConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LlmModelConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LlmModelConfigGroupByOutputType[P]>
      }
    >
  >



export type LlmModelConfigWhereInput = {
  AND?: Prisma.LlmModelConfigWhereInput | Prisma.LlmModelConfigWhereInput[]
  OR?: Prisma.LlmModelConfigWhereInput[]
  NOT?: Prisma.LlmModelConfigWhereInput | Prisma.LlmModelConfigWhereInput[]
  id?: Prisma.IntFilter<"LlmModelConfig"> | number
  created_at?: Prisma.DateTimeFilter<"LlmModelConfig"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"LlmModelConfig"> | Date | string
  key?: Prisma.StringFilter<"LlmModelConfig"> | string
  model_id?: Prisma.StringFilter<"LlmModelConfig"> | string
  provider?: Prisma.StringFilter<"LlmModelConfig"> | string
  description?: Prisma.StringNullableFilter<"LlmModelConfig"> | string | null
  is_active?: Prisma.BoolFilter<"LlmModelConfig"> | boolean
}

export type LlmModelConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  key?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type LlmModelConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  key?: string
  AND?: Prisma.LlmModelConfigWhereInput | Prisma.LlmModelConfigWhereInput[]
  OR?: Prisma.LlmModelConfigWhereInput[]
  NOT?: Prisma.LlmModelConfigWhereInput | Prisma.LlmModelConfigWhereInput[]
  created_at?: Prisma.DateTimeFilter<"LlmModelConfig"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"LlmModelConfig"> | Date | string
  model_id?: Prisma.StringFilter<"LlmModelConfig"> | string
  provider?: Prisma.StringFilter<"LlmModelConfig"> | string
  description?: Prisma.StringNullableFilter<"LlmModelConfig"> | string | null
  is_active?: Prisma.BoolFilter<"LlmModelConfig"> | boolean
}, "id" | "id" | "key">

export type LlmModelConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  key?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrder
  _count?: Prisma.LlmModelConfigCountOrderByAggregateInput
  _avg?: Prisma.LlmModelConfigAvgOrderByAggregateInput
  _max?: Prisma.LlmModelConfigMaxOrderByAggregateInput
  _min?: Prisma.LlmModelConfigMinOrderByAggregateInput
  _sum?: Prisma.LlmModelConfigSumOrderByAggregateInput
}

export type LlmModelConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.LlmModelConfigScalarWhereWithAggregatesInput | Prisma.LlmModelConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.LlmModelConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LlmModelConfigScalarWhereWithAggregatesInput | Prisma.LlmModelConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"LlmModelConfig"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"LlmModelConfig"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"LlmModelConfig"> | Date | string
  key?: Prisma.StringWithAggregatesFilter<"LlmModelConfig"> | string
  model_id?: Prisma.StringWithAggregatesFilter<"LlmModelConfig"> | string
  provider?: Prisma.StringWithAggregatesFilter<"LlmModelConfig"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"LlmModelConfig"> | string | null
  is_active?: Prisma.BoolWithAggregatesFilter<"LlmModelConfig"> | boolean
}

export type LlmModelConfigCreateInput = {
  created_at?: Date | string
  updated_at?: Date | string
  key: string
  model_id: string
  provider?: string
  description?: string | null
  is_active?: boolean
}

export type LlmModelConfigUncheckedCreateInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  key: string
  model_id: string
  provider?: string
  description?: string | null
  is_active?: boolean
}

export type LlmModelConfigUpdateInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type LlmModelConfigUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type LlmModelConfigCreateManyInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  key: string
  model_id: string
  provider?: string
  description?: string | null
  is_active?: boolean
}

export type LlmModelConfigUpdateManyMutationInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type LlmModelConfigUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type LlmModelConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  key?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type LlmModelConfigAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type LlmModelConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  key?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type LlmModelConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  key?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type LlmModelConfigSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type LlmModelConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  key?: boolean
  model_id?: boolean
  provider?: boolean
  description?: boolean
  is_active?: boolean
}, ExtArgs["result"]["llmModelConfig"]>

export type LlmModelConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  key?: boolean
  model_id?: boolean
  provider?: boolean
  description?: boolean
  is_active?: boolean
}, ExtArgs["result"]["llmModelConfig"]>

export type LlmModelConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  key?: boolean
  model_id?: boolean
  provider?: boolean
  description?: boolean
  is_active?: boolean
}, ExtArgs["result"]["llmModelConfig"]>

export type LlmModelConfigSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  key?: boolean
  model_id?: boolean
  provider?: boolean
  description?: boolean
  is_active?: boolean
}

export type LlmModelConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "key" | "model_id" | "provider" | "description" | "is_active", ExtArgs["result"]["llmModelConfig"]>

export type $LlmModelConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LlmModelConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    created_at: Date
    updated_at: Date
    key: string
    model_id: string
    provider: string
    description: string | null
    is_active: boolean
  }, ExtArgs["result"]["llmModelConfig"]>
  composites: {}
}

export type LlmModelConfigGetPayload<S extends boolean | null | undefined | LlmModelConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload, S>

export type LlmModelConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LlmModelConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LlmModelConfigCountAggregateInputType | true
  }

export interface LlmModelConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LlmModelConfig'], meta: { name: 'LlmModelConfig' } }
  /**
   * Find zero or one LlmModelConfig that matches the filter.
   * @param {LlmModelConfigFindUniqueArgs} args - Arguments to find a LlmModelConfig
   * @example
   * // Get one LlmModelConfig
   * const llmModelConfig = await prisma.llmModelConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LlmModelConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, LlmModelConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LlmModelConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LlmModelConfigFindUniqueOrThrowArgs} args - Arguments to find a LlmModelConfig
   * @example
   * // Get one LlmModelConfig
   * const llmModelConfig = await prisma.llmModelConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LlmModelConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LlmModelConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LlmModelConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigFindFirstArgs} args - Arguments to find a LlmModelConfig
   * @example
   * // Get one LlmModelConfig
   * const llmModelConfig = await prisma.llmModelConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LlmModelConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, LlmModelConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LlmModelConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigFindFirstOrThrowArgs} args - Arguments to find a LlmModelConfig
   * @example
   * // Get one LlmModelConfig
   * const llmModelConfig = await prisma.llmModelConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LlmModelConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LlmModelConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LlmModelConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LlmModelConfigs
   * const llmModelConfigs = await prisma.llmModelConfig.findMany()
   * 
   * // Get first 10 LlmModelConfigs
   * const llmModelConfigs = await prisma.llmModelConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const llmModelConfigWithIdOnly = await prisma.llmModelConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LlmModelConfigFindManyArgs>(args?: Prisma.SelectSubset<T, LlmModelConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LlmModelConfig.
   * @param {LlmModelConfigCreateArgs} args - Arguments to create a LlmModelConfig.
   * @example
   * // Create one LlmModelConfig
   * const LlmModelConfig = await prisma.llmModelConfig.create({
   *   data: {
   *     // ... data to create a LlmModelConfig
   *   }
   * })
   * 
   */
  create<T extends LlmModelConfigCreateArgs>(args: Prisma.SelectSubset<T, LlmModelConfigCreateArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LlmModelConfigs.
   * @param {LlmModelConfigCreateManyArgs} args - Arguments to create many LlmModelConfigs.
   * @example
   * // Create many LlmModelConfigs
   * const llmModelConfig = await prisma.llmModelConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LlmModelConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, LlmModelConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LlmModelConfigs and returns the data saved in the database.
   * @param {LlmModelConfigCreateManyAndReturnArgs} args - Arguments to create many LlmModelConfigs.
   * @example
   * // Create many LlmModelConfigs
   * const llmModelConfig = await prisma.llmModelConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LlmModelConfigs and only return the `id`
   * const llmModelConfigWithIdOnly = await prisma.llmModelConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LlmModelConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LlmModelConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LlmModelConfig.
   * @param {LlmModelConfigDeleteArgs} args - Arguments to delete one LlmModelConfig.
   * @example
   * // Delete one LlmModelConfig
   * const LlmModelConfig = await prisma.llmModelConfig.delete({
   *   where: {
   *     // ... filter to delete one LlmModelConfig
   *   }
   * })
   * 
   */
  delete<T extends LlmModelConfigDeleteArgs>(args: Prisma.SelectSubset<T, LlmModelConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LlmModelConfig.
   * @param {LlmModelConfigUpdateArgs} args - Arguments to update one LlmModelConfig.
   * @example
   * // Update one LlmModelConfig
   * const llmModelConfig = await prisma.llmModelConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LlmModelConfigUpdateArgs>(args: Prisma.SelectSubset<T, LlmModelConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LlmModelConfigs.
   * @param {LlmModelConfigDeleteManyArgs} args - Arguments to filter LlmModelConfigs to delete.
   * @example
   * // Delete a few LlmModelConfigs
   * const { count } = await prisma.llmModelConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LlmModelConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, LlmModelConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LlmModelConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LlmModelConfigs
   * const llmModelConfig = await prisma.llmModelConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LlmModelConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, LlmModelConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LlmModelConfigs and returns the data updated in the database.
   * @param {LlmModelConfigUpdateManyAndReturnArgs} args - Arguments to update many LlmModelConfigs.
   * @example
   * // Update many LlmModelConfigs
   * const llmModelConfig = await prisma.llmModelConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LlmModelConfigs and only return the `id`
   * const llmModelConfigWithIdOnly = await prisma.llmModelConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LlmModelConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LlmModelConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LlmModelConfig.
   * @param {LlmModelConfigUpsertArgs} args - Arguments to update or create a LlmModelConfig.
   * @example
   * // Update or create a LlmModelConfig
   * const llmModelConfig = await prisma.llmModelConfig.upsert({
   *   create: {
   *     // ... data to create a LlmModelConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LlmModelConfig we want to update
   *   }
   * })
   */
  upsert<T extends LlmModelConfigUpsertArgs>(args: Prisma.SelectSubset<T, LlmModelConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__LlmModelConfigClient<runtime.Types.Result.GetResult<Prisma.$LlmModelConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LlmModelConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigCountArgs} args - Arguments to filter LlmModelConfigs to count.
   * @example
   * // Count the number of LlmModelConfigs
   * const count = await prisma.llmModelConfig.count({
   *   where: {
   *     // ... the filter for the LlmModelConfigs we want to count
   *   }
   * })
  **/
  count<T extends LlmModelConfigCountArgs>(
    args?: Prisma.Subset<T, LlmModelConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LlmModelConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LlmModelConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LlmModelConfigAggregateArgs>(args: Prisma.Subset<T, LlmModelConfigAggregateArgs>): Prisma.PrismaPromise<GetLlmModelConfigAggregateType<T>>

  /**
   * Group by LlmModelConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LlmModelConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LlmModelConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LlmModelConfigGroupByArgs['orderBy'] }
      : { orderBy?: LlmModelConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LlmModelConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLlmModelConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LlmModelConfig model
 */
readonly fields: LlmModelConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LlmModelConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LlmModelConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LlmModelConfig model
 */
export interface LlmModelConfigFieldRefs {
  readonly id: Prisma.FieldRef<"LlmModelConfig", 'Int'>
  readonly created_at: Prisma.FieldRef<"LlmModelConfig", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"LlmModelConfig", 'DateTime'>
  readonly key: Prisma.FieldRef<"LlmModelConfig", 'String'>
  readonly model_id: Prisma.FieldRef<"LlmModelConfig", 'String'>
  readonly provider: Prisma.FieldRef<"LlmModelConfig", 'String'>
  readonly description: Prisma.FieldRef<"LlmModelConfig", 'String'>
  readonly is_active: Prisma.FieldRef<"LlmModelConfig", 'Boolean'>
}
    

// Custom InputTypes
/**
 * LlmModelConfig findUnique
 */
export type LlmModelConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * Filter, which LlmModelConfig to fetch.
   */
  where: Prisma.LlmModelConfigWhereUniqueInput
}

/**
 * LlmModelConfig findUniqueOrThrow
 */
export type LlmModelConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * Filter, which LlmModelConfig to fetch.
   */
  where: Prisma.LlmModelConfigWhereUniqueInput
}

/**
 * LlmModelConfig findFirst
 */
export type LlmModelConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * Filter, which LlmModelConfig to fetch.
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LlmModelConfigs to fetch.
   */
  orderBy?: Prisma.LlmModelConfigOrderByWithRelationInput | Prisma.LlmModelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LlmModelConfigs.
   */
  cursor?: Prisma.LlmModelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LlmModelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LlmModelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LlmModelConfigs.
   */
  distinct?: Prisma.LlmModelConfigScalarFieldEnum | Prisma.LlmModelConfigScalarFieldEnum[]
}

/**
 * LlmModelConfig findFirstOrThrow
 */
export type LlmModelConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * Filter, which LlmModelConfig to fetch.
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LlmModelConfigs to fetch.
   */
  orderBy?: Prisma.LlmModelConfigOrderByWithRelationInput | Prisma.LlmModelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LlmModelConfigs.
   */
  cursor?: Prisma.LlmModelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LlmModelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LlmModelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LlmModelConfigs.
   */
  distinct?: Prisma.LlmModelConfigScalarFieldEnum | Prisma.LlmModelConfigScalarFieldEnum[]
}

/**
 * LlmModelConfig findMany
 */
export type LlmModelConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * Filter, which LlmModelConfigs to fetch.
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LlmModelConfigs to fetch.
   */
  orderBy?: Prisma.LlmModelConfigOrderByWithRelationInput | Prisma.LlmModelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LlmModelConfigs.
   */
  cursor?: Prisma.LlmModelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LlmModelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LlmModelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LlmModelConfigs.
   */
  distinct?: Prisma.LlmModelConfigScalarFieldEnum | Prisma.LlmModelConfigScalarFieldEnum[]
}

/**
 * LlmModelConfig create
 */
export type LlmModelConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a LlmModelConfig.
   */
  data: Prisma.XOR<Prisma.LlmModelConfigCreateInput, Prisma.LlmModelConfigUncheckedCreateInput>
}

/**
 * LlmModelConfig createMany
 */
export type LlmModelConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LlmModelConfigs.
   */
  data: Prisma.LlmModelConfigCreateManyInput | Prisma.LlmModelConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LlmModelConfig createManyAndReturn
 */
export type LlmModelConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * The data used to create many LlmModelConfigs.
   */
  data: Prisma.LlmModelConfigCreateManyInput | Prisma.LlmModelConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LlmModelConfig update
 */
export type LlmModelConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a LlmModelConfig.
   */
  data: Prisma.XOR<Prisma.LlmModelConfigUpdateInput, Prisma.LlmModelConfigUncheckedUpdateInput>
  /**
   * Choose, which LlmModelConfig to update.
   */
  where: Prisma.LlmModelConfigWhereUniqueInput
}

/**
 * LlmModelConfig updateMany
 */
export type LlmModelConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LlmModelConfigs.
   */
  data: Prisma.XOR<Prisma.LlmModelConfigUpdateManyMutationInput, Prisma.LlmModelConfigUncheckedUpdateManyInput>
  /**
   * Filter which LlmModelConfigs to update
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * Limit how many LlmModelConfigs to update.
   */
  limit?: number
}

/**
 * LlmModelConfig updateManyAndReturn
 */
export type LlmModelConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * The data used to update LlmModelConfigs.
   */
  data: Prisma.XOR<Prisma.LlmModelConfigUpdateManyMutationInput, Prisma.LlmModelConfigUncheckedUpdateManyInput>
  /**
   * Filter which LlmModelConfigs to update
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * Limit how many LlmModelConfigs to update.
   */
  limit?: number
}

/**
 * LlmModelConfig upsert
 */
export type LlmModelConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the LlmModelConfig to update in case it exists.
   */
  where: Prisma.LlmModelConfigWhereUniqueInput
  /**
   * In case the LlmModelConfig found by the `where` argument doesn't exist, create a new LlmModelConfig with this data.
   */
  create: Prisma.XOR<Prisma.LlmModelConfigCreateInput, Prisma.LlmModelConfigUncheckedCreateInput>
  /**
   * In case the LlmModelConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LlmModelConfigUpdateInput, Prisma.LlmModelConfigUncheckedUpdateInput>
}

/**
 * LlmModelConfig delete
 */
export type LlmModelConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
  /**
   * Filter which LlmModelConfig to delete.
   */
  where: Prisma.LlmModelConfigWhereUniqueInput
}

/**
 * LlmModelConfig deleteMany
 */
export type LlmModelConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LlmModelConfigs to delete
   */
  where?: Prisma.LlmModelConfigWhereInput
  /**
   * Limit how many LlmModelConfigs to delete.
   */
  limit?: number
}

/**
 * LlmModelConfig without action
 */
export type LlmModelConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LlmModelConfig
   */
  select?: Prisma.LlmModelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LlmModelConfig
   */
  omit?: Prisma.LlmModelConfigOmit<ExtArgs> | null
}
