
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MarkScheme` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model MarkScheme
 * 
 */
export type MarkSchemeModel = runtime.Types.Result.DefaultSelection<Prisma.$MarkSchemePayload>

export type AggregateMarkScheme = {
  _count: MarkSchemeCountAggregateOutputType | null
  _avg: MarkSchemeAvgAggregateOutputType | null
  _sum: MarkSchemeSumAggregateOutputType | null
  _min: MarkSchemeMinAggregateOutputType | null
  _max: MarkSchemeMaxAggregateOutputType | null
}

export type MarkSchemeAvgAggregateOutputType = {
  id: number | null
}

export type MarkSchemeSumAggregateOutputType = {
  id: number | null
}

export type MarkSchemeMinAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  mark_scheme_id: string | null
  paper_id: string | null
  status: $Enums.MarkSchemeStatus | null
  prompt_version: string | null
  raw_content: string | null
}

export type MarkSchemeMaxAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  mark_scheme_id: string | null
  paper_id: string | null
  status: $Enums.MarkSchemeStatus | null
  prompt_version: string | null
  raw_content: string | null
}

export type MarkSchemeCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  mark_scheme_id: number
  paper_id: number
  status: number
  model_answer: number
  points: number
  prompt_version: number
  raw_content: number
  _all: number
}


export type MarkSchemeAvgAggregateInputType = {
  id?: true
}

export type MarkSchemeSumAggregateInputType = {
  id?: true
}

export type MarkSchemeMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  mark_scheme_id?: true
  paper_id?: true
  status?: true
  prompt_version?: true
  raw_content?: true
}

export type MarkSchemeMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  mark_scheme_id?: true
  paper_id?: true
  status?: true
  prompt_version?: true
  raw_content?: true
}

export type MarkSchemeCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  mark_scheme_id?: true
  paper_id?: true
  status?: true
  model_answer?: true
  points?: true
  prompt_version?: true
  raw_content?: true
  _all?: true
}

export type MarkSchemeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarkScheme to aggregate.
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarkSchemes to fetch.
   */
  orderBy?: Prisma.MarkSchemeOrderByWithRelationInput | Prisma.MarkSchemeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MarkSchemeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarkSchemes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarkSchemes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MarkSchemes
  **/
  _count?: true | MarkSchemeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MarkSchemeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MarkSchemeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MarkSchemeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MarkSchemeMaxAggregateInputType
}

export type GetMarkSchemeAggregateType<T extends MarkSchemeAggregateArgs> = {
      [P in keyof T & keyof AggregateMarkScheme]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMarkScheme[P]>
    : Prisma.GetScalarType<T[P], AggregateMarkScheme[P]>
}




export type MarkSchemeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MarkSchemeWhereInput
  orderBy?: Prisma.MarkSchemeOrderByWithAggregationInput | Prisma.MarkSchemeOrderByWithAggregationInput[]
  by: Prisma.MarkSchemeScalarFieldEnum[] | Prisma.MarkSchemeScalarFieldEnum
  having?: Prisma.MarkSchemeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MarkSchemeCountAggregateInputType | true
  _avg?: MarkSchemeAvgAggregateInputType
  _sum?: MarkSchemeSumAggregateInputType
  _min?: MarkSchemeMinAggregateInputType
  _max?: MarkSchemeMaxAggregateInputType
}

export type MarkSchemeGroupByOutputType = {
  id: number
  created_at: Date
  updated_at: Date
  mark_scheme_id: string
  paper_id: string
  status: $Enums.MarkSchemeStatus
  model_answer: runtime.JsonValue | null
  points: runtime.JsonValue | null
  prompt_version: string | null
  raw_content: string | null
  _count: MarkSchemeCountAggregateOutputType | null
  _avg: MarkSchemeAvgAggregateOutputType | null
  _sum: MarkSchemeSumAggregateOutputType | null
  _min: MarkSchemeMinAggregateOutputType | null
  _max: MarkSchemeMaxAggregateOutputType | null
}

export type GetMarkSchemeGroupByPayload<T extends MarkSchemeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MarkSchemeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MarkSchemeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MarkSchemeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MarkSchemeGroupByOutputType[P]>
      }
    >
  >



export type MarkSchemeWhereInput = {
  AND?: Prisma.MarkSchemeWhereInput | Prisma.MarkSchemeWhereInput[]
  OR?: Prisma.MarkSchemeWhereInput[]
  NOT?: Prisma.MarkSchemeWhereInput | Prisma.MarkSchemeWhereInput[]
  id?: Prisma.IntFilter<"MarkScheme"> | number
  created_at?: Prisma.DateTimeFilter<"MarkScheme"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"MarkScheme"> | Date | string
  mark_scheme_id?: Prisma.StringFilter<"MarkScheme"> | string
  paper_id?: Prisma.StringFilter<"MarkScheme"> | string
  status?: Prisma.EnumMarkSchemeStatusFilter<"MarkScheme"> | $Enums.MarkSchemeStatus
  model_answer?: Prisma.JsonNullableFilter<"MarkScheme">
  points?: Prisma.JsonNullableFilter<"MarkScheme">
  prompt_version?: Prisma.StringNullableFilter<"MarkScheme"> | string | null
  raw_content?: Prisma.StringNullableFilter<"MarkScheme"> | string | null
  paper?: Prisma.XOR<Prisma.PaperScalarRelationFilter, Prisma.PaperWhereInput>
}

export type MarkSchemeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  mark_scheme_id?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  model_answer?: Prisma.SortOrderInput | Prisma.SortOrder
  points?: Prisma.SortOrderInput | Prisma.SortOrder
  prompt_version?: Prisma.SortOrderInput | Prisma.SortOrder
  raw_content?: Prisma.SortOrderInput | Prisma.SortOrder
  paper?: Prisma.PaperOrderByWithRelationInput
}

export type MarkSchemeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  mark_scheme_id?: string
  paper_id?: string
  AND?: Prisma.MarkSchemeWhereInput | Prisma.MarkSchemeWhereInput[]
  OR?: Prisma.MarkSchemeWhereInput[]
  NOT?: Prisma.MarkSchemeWhereInput | Prisma.MarkSchemeWhereInput[]
  created_at?: Prisma.DateTimeFilter<"MarkScheme"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"MarkScheme"> | Date | string
  status?: Prisma.EnumMarkSchemeStatusFilter<"MarkScheme"> | $Enums.MarkSchemeStatus
  model_answer?: Prisma.JsonNullableFilter<"MarkScheme">
  points?: Prisma.JsonNullableFilter<"MarkScheme">
  prompt_version?: Prisma.StringNullableFilter<"MarkScheme"> | string | null
  raw_content?: Prisma.StringNullableFilter<"MarkScheme"> | string | null
  paper?: Prisma.XOR<Prisma.PaperScalarRelationFilter, Prisma.PaperWhereInput>
}, "id" | "id" | "mark_scheme_id" | "paper_id">

export type MarkSchemeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  mark_scheme_id?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  model_answer?: Prisma.SortOrderInput | Prisma.SortOrder
  points?: Prisma.SortOrderInput | Prisma.SortOrder
  prompt_version?: Prisma.SortOrderInput | Prisma.SortOrder
  raw_content?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MarkSchemeCountOrderByAggregateInput
  _avg?: Prisma.MarkSchemeAvgOrderByAggregateInput
  _max?: Prisma.MarkSchemeMaxOrderByAggregateInput
  _min?: Prisma.MarkSchemeMinOrderByAggregateInput
  _sum?: Prisma.MarkSchemeSumOrderByAggregateInput
}

export type MarkSchemeScalarWhereWithAggregatesInput = {
  AND?: Prisma.MarkSchemeScalarWhereWithAggregatesInput | Prisma.MarkSchemeScalarWhereWithAggregatesInput[]
  OR?: Prisma.MarkSchemeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MarkSchemeScalarWhereWithAggregatesInput | Prisma.MarkSchemeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MarkScheme"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"MarkScheme"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"MarkScheme"> | Date | string
  mark_scheme_id?: Prisma.StringWithAggregatesFilter<"MarkScheme"> | string
  paper_id?: Prisma.StringWithAggregatesFilter<"MarkScheme"> | string
  status?: Prisma.EnumMarkSchemeStatusWithAggregatesFilter<"MarkScheme"> | $Enums.MarkSchemeStatus
  model_answer?: Prisma.JsonNullableWithAggregatesFilter<"MarkScheme">
  points?: Prisma.JsonNullableWithAggregatesFilter<"MarkScheme">
  prompt_version?: Prisma.StringNullableWithAggregatesFilter<"MarkScheme"> | string | null
  raw_content?: Prisma.StringNullableWithAggregatesFilter<"MarkScheme"> | string | null
}

export type MarkSchemeCreateInput = {
  created_at?: Date | string
  updated_at?: Date | string
  mark_scheme_id: string
  status?: $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: string | null
  raw_content?: string | null
  paper: Prisma.PaperCreateNestedOneWithoutMarkSchemeInput
}

export type MarkSchemeUncheckedCreateInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  mark_scheme_id: string
  paper_id: string
  status?: $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: string | null
  raw_content?: string | null
}

export type MarkSchemeUpdateInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mark_scheme_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMarkSchemeStatusFieldUpdateOperationsInput | $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paper?: Prisma.PaperUpdateOneRequiredWithoutMarkSchemeNestedInput
}

export type MarkSchemeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mark_scheme_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMarkSchemeStatusFieldUpdateOperationsInput | $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MarkSchemeCreateManyInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  mark_scheme_id: string
  paper_id: string
  status?: $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: string | null
  raw_content?: string | null
}

export type MarkSchemeUpdateManyMutationInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mark_scheme_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMarkSchemeStatusFieldUpdateOperationsInput | $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MarkSchemeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mark_scheme_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMarkSchemeStatusFieldUpdateOperationsInput | $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MarkSchemeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  mark_scheme_id?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  model_answer?: Prisma.SortOrder
  points?: Prisma.SortOrder
  prompt_version?: Prisma.SortOrder
  raw_content?: Prisma.SortOrder
}

export type MarkSchemeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MarkSchemeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  mark_scheme_id?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  prompt_version?: Prisma.SortOrder
  raw_content?: Prisma.SortOrder
}

export type MarkSchemeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  mark_scheme_id?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  prompt_version?: Prisma.SortOrder
  raw_content?: Prisma.SortOrder
}

export type MarkSchemeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MarkSchemeNullableScalarRelationFilter = {
  is?: Prisma.MarkSchemeWhereInput | null
  isNot?: Prisma.MarkSchemeWhereInput | null
}

export type EnumMarkSchemeStatusFieldUpdateOperationsInput = {
  set?: $Enums.MarkSchemeStatus
}

export type MarkSchemeCreateNestedOneWithoutPaperInput = {
  create?: Prisma.XOR<Prisma.MarkSchemeCreateWithoutPaperInput, Prisma.MarkSchemeUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.MarkSchemeCreateOrConnectWithoutPaperInput
  connect?: Prisma.MarkSchemeWhereUniqueInput
}

export type MarkSchemeUncheckedCreateNestedOneWithoutPaperInput = {
  create?: Prisma.XOR<Prisma.MarkSchemeCreateWithoutPaperInput, Prisma.MarkSchemeUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.MarkSchemeCreateOrConnectWithoutPaperInput
  connect?: Prisma.MarkSchemeWhereUniqueInput
}

export type MarkSchemeUpdateOneWithoutPaperNestedInput = {
  create?: Prisma.XOR<Prisma.MarkSchemeCreateWithoutPaperInput, Prisma.MarkSchemeUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.MarkSchemeCreateOrConnectWithoutPaperInput
  upsert?: Prisma.MarkSchemeUpsertWithoutPaperInput
  disconnect?: Prisma.MarkSchemeWhereInput | boolean
  delete?: Prisma.MarkSchemeWhereInput | boolean
  connect?: Prisma.MarkSchemeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MarkSchemeUpdateToOneWithWhereWithoutPaperInput, Prisma.MarkSchemeUpdateWithoutPaperInput>, Prisma.MarkSchemeUncheckedUpdateWithoutPaperInput>
}

export type MarkSchemeUncheckedUpdateOneWithoutPaperNestedInput = {
  create?: Prisma.XOR<Prisma.MarkSchemeCreateWithoutPaperInput, Prisma.MarkSchemeUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.MarkSchemeCreateOrConnectWithoutPaperInput
  upsert?: Prisma.MarkSchemeUpsertWithoutPaperInput
  disconnect?: Prisma.MarkSchemeWhereInput | boolean
  delete?: Prisma.MarkSchemeWhereInput | boolean
  connect?: Prisma.MarkSchemeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MarkSchemeUpdateToOneWithWhereWithoutPaperInput, Prisma.MarkSchemeUpdateWithoutPaperInput>, Prisma.MarkSchemeUncheckedUpdateWithoutPaperInput>
}

export type MarkSchemeCreateWithoutPaperInput = {
  created_at?: Date | string
  updated_at?: Date | string
  mark_scheme_id: string
  status?: $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: string | null
  raw_content?: string | null
}

export type MarkSchemeUncheckedCreateWithoutPaperInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  mark_scheme_id: string
  status?: $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: string | null
  raw_content?: string | null
}

export type MarkSchemeCreateOrConnectWithoutPaperInput = {
  where: Prisma.MarkSchemeWhereUniqueInput
  create: Prisma.XOR<Prisma.MarkSchemeCreateWithoutPaperInput, Prisma.MarkSchemeUncheckedCreateWithoutPaperInput>
}

export type MarkSchemeUpsertWithoutPaperInput = {
  update: Prisma.XOR<Prisma.MarkSchemeUpdateWithoutPaperInput, Prisma.MarkSchemeUncheckedUpdateWithoutPaperInput>
  create: Prisma.XOR<Prisma.MarkSchemeCreateWithoutPaperInput, Prisma.MarkSchemeUncheckedCreateWithoutPaperInput>
  where?: Prisma.MarkSchemeWhereInput
}

export type MarkSchemeUpdateToOneWithWhereWithoutPaperInput = {
  where?: Prisma.MarkSchemeWhereInput
  data: Prisma.XOR<Prisma.MarkSchemeUpdateWithoutPaperInput, Prisma.MarkSchemeUncheckedUpdateWithoutPaperInput>
}

export type MarkSchemeUpdateWithoutPaperInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mark_scheme_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMarkSchemeStatusFieldUpdateOperationsInput | $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MarkSchemeUncheckedUpdateWithoutPaperInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mark_scheme_id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumMarkSchemeStatusFieldUpdateOperationsInput | $Enums.MarkSchemeStatus
  model_answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  points?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  prompt_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  raw_content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type MarkSchemeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  mark_scheme_id?: boolean
  paper_id?: boolean
  status?: boolean
  model_answer?: boolean
  points?: boolean
  prompt_version?: boolean
  raw_content?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["markScheme"]>

export type MarkSchemeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  mark_scheme_id?: boolean
  paper_id?: boolean
  status?: boolean
  model_answer?: boolean
  points?: boolean
  prompt_version?: boolean
  raw_content?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["markScheme"]>

export type MarkSchemeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  mark_scheme_id?: boolean
  paper_id?: boolean
  status?: boolean
  model_answer?: boolean
  points?: boolean
  prompt_version?: boolean
  raw_content?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["markScheme"]>

export type MarkSchemeSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  mark_scheme_id?: boolean
  paper_id?: boolean
  status?: boolean
  model_answer?: boolean
  points?: boolean
  prompt_version?: boolean
  raw_content?: boolean
}

export type MarkSchemeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "mark_scheme_id" | "paper_id" | "status" | "model_answer" | "points" | "prompt_version" | "raw_content", ExtArgs["result"]["markScheme"]>
export type MarkSchemeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}
export type MarkSchemeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}
export type MarkSchemeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}

export type $MarkSchemePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MarkScheme"
  objects: {
    paper: Prisma.$PaperPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    created_at: Date
    updated_at: Date
    mark_scheme_id: string
    paper_id: string
    status: $Enums.MarkSchemeStatus
    model_answer: runtime.JsonValue | null
    points: runtime.JsonValue | null
    prompt_version: string | null
    raw_content: string | null
  }, ExtArgs["result"]["markScheme"]>
  composites: {}
}

export type MarkSchemeGetPayload<S extends boolean | null | undefined | MarkSchemeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload, S>

export type MarkSchemeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MarkSchemeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MarkSchemeCountAggregateInputType | true
  }

export interface MarkSchemeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MarkScheme'], meta: { name: 'MarkScheme' } }
  /**
   * Find zero or one MarkScheme that matches the filter.
   * @param {MarkSchemeFindUniqueArgs} args - Arguments to find a MarkScheme
   * @example
   * // Get one MarkScheme
   * const markScheme = await prisma.markScheme.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MarkSchemeFindUniqueArgs>(args: Prisma.SelectSubset<T, MarkSchemeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MarkScheme that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MarkSchemeFindUniqueOrThrowArgs} args - Arguments to find a MarkScheme
   * @example
   * // Get one MarkScheme
   * const markScheme = await prisma.markScheme.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MarkSchemeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MarkSchemeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarkScheme that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeFindFirstArgs} args - Arguments to find a MarkScheme
   * @example
   * // Get one MarkScheme
   * const markScheme = await prisma.markScheme.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MarkSchemeFindFirstArgs>(args?: Prisma.SelectSubset<T, MarkSchemeFindFirstArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarkScheme that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeFindFirstOrThrowArgs} args - Arguments to find a MarkScheme
   * @example
   * // Get one MarkScheme
   * const markScheme = await prisma.markScheme.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MarkSchemeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MarkSchemeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MarkSchemes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MarkSchemes
   * const markSchemes = await prisma.markScheme.findMany()
   * 
   * // Get first 10 MarkSchemes
   * const markSchemes = await prisma.markScheme.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const markSchemeWithIdOnly = await prisma.markScheme.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MarkSchemeFindManyArgs>(args?: Prisma.SelectSubset<T, MarkSchemeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MarkScheme.
   * @param {MarkSchemeCreateArgs} args - Arguments to create a MarkScheme.
   * @example
   * // Create one MarkScheme
   * const MarkScheme = await prisma.markScheme.create({
   *   data: {
   *     // ... data to create a MarkScheme
   *   }
   * })
   * 
   */
  create<T extends MarkSchemeCreateArgs>(args: Prisma.SelectSubset<T, MarkSchemeCreateArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MarkSchemes.
   * @param {MarkSchemeCreateManyArgs} args - Arguments to create many MarkSchemes.
   * @example
   * // Create many MarkSchemes
   * const markScheme = await prisma.markScheme.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MarkSchemeCreateManyArgs>(args?: Prisma.SelectSubset<T, MarkSchemeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MarkSchemes and returns the data saved in the database.
   * @param {MarkSchemeCreateManyAndReturnArgs} args - Arguments to create many MarkSchemes.
   * @example
   * // Create many MarkSchemes
   * const markScheme = await prisma.markScheme.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MarkSchemes and only return the `id`
   * const markSchemeWithIdOnly = await prisma.markScheme.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MarkSchemeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MarkSchemeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MarkScheme.
   * @param {MarkSchemeDeleteArgs} args - Arguments to delete one MarkScheme.
   * @example
   * // Delete one MarkScheme
   * const MarkScheme = await prisma.markScheme.delete({
   *   where: {
   *     // ... filter to delete one MarkScheme
   *   }
   * })
   * 
   */
  delete<T extends MarkSchemeDeleteArgs>(args: Prisma.SelectSubset<T, MarkSchemeDeleteArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MarkScheme.
   * @param {MarkSchemeUpdateArgs} args - Arguments to update one MarkScheme.
   * @example
   * // Update one MarkScheme
   * const markScheme = await prisma.markScheme.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MarkSchemeUpdateArgs>(args: Prisma.SelectSubset<T, MarkSchemeUpdateArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MarkSchemes.
   * @param {MarkSchemeDeleteManyArgs} args - Arguments to filter MarkSchemes to delete.
   * @example
   * // Delete a few MarkSchemes
   * const { count } = await prisma.markScheme.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MarkSchemeDeleteManyArgs>(args?: Prisma.SelectSubset<T, MarkSchemeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarkSchemes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MarkSchemes
   * const markScheme = await prisma.markScheme.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MarkSchemeUpdateManyArgs>(args: Prisma.SelectSubset<T, MarkSchemeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarkSchemes and returns the data updated in the database.
   * @param {MarkSchemeUpdateManyAndReturnArgs} args - Arguments to update many MarkSchemes.
   * @example
   * // Update many MarkSchemes
   * const markScheme = await prisma.markScheme.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MarkSchemes and only return the `id`
   * const markSchemeWithIdOnly = await prisma.markScheme.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MarkSchemeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MarkSchemeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MarkScheme.
   * @param {MarkSchemeUpsertArgs} args - Arguments to update or create a MarkScheme.
   * @example
   * // Update or create a MarkScheme
   * const markScheme = await prisma.markScheme.upsert({
   *   create: {
   *     // ... data to create a MarkScheme
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MarkScheme we want to update
   *   }
   * })
   */
  upsert<T extends MarkSchemeUpsertArgs>(args: Prisma.SelectSubset<T, MarkSchemeUpsertArgs<ExtArgs>>): Prisma.Prisma__MarkSchemeClient<runtime.Types.Result.GetResult<Prisma.$MarkSchemePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MarkSchemes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeCountArgs} args - Arguments to filter MarkSchemes to count.
   * @example
   * // Count the number of MarkSchemes
   * const count = await prisma.markScheme.count({
   *   where: {
   *     // ... the filter for the MarkSchemes we want to count
   *   }
   * })
  **/
  count<T extends MarkSchemeCountArgs>(
    args?: Prisma.Subset<T, MarkSchemeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MarkSchemeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MarkScheme.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MarkSchemeAggregateArgs>(args: Prisma.Subset<T, MarkSchemeAggregateArgs>): Prisma.PrismaPromise<GetMarkSchemeAggregateType<T>>

  /**
   * Group by MarkScheme.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarkSchemeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MarkSchemeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MarkSchemeGroupByArgs['orderBy'] }
      : { orderBy?: MarkSchemeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MarkSchemeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMarkSchemeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MarkScheme model
 */
readonly fields: MarkSchemeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MarkScheme.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MarkSchemeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  paper<T extends Prisma.PaperDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PaperDefaultArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MarkScheme model
 */
export interface MarkSchemeFieldRefs {
  readonly id: Prisma.FieldRef<"MarkScheme", 'Int'>
  readonly created_at: Prisma.FieldRef<"MarkScheme", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"MarkScheme", 'DateTime'>
  readonly mark_scheme_id: Prisma.FieldRef<"MarkScheme", 'String'>
  readonly paper_id: Prisma.FieldRef<"MarkScheme", 'String'>
  readonly status: Prisma.FieldRef<"MarkScheme", 'MarkSchemeStatus'>
  readonly model_answer: Prisma.FieldRef<"MarkScheme", 'Json'>
  readonly points: Prisma.FieldRef<"MarkScheme", 'Json'>
  readonly prompt_version: Prisma.FieldRef<"MarkScheme", 'String'>
  readonly raw_content: Prisma.FieldRef<"MarkScheme", 'String'>
}
    

// Custom InputTypes
/**
 * MarkScheme findUnique
 */
export type MarkSchemeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * Filter, which MarkScheme to fetch.
   */
  where: Prisma.MarkSchemeWhereUniqueInput
}

/**
 * MarkScheme findUniqueOrThrow
 */
export type MarkSchemeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * Filter, which MarkScheme to fetch.
   */
  where: Prisma.MarkSchemeWhereUniqueInput
}

/**
 * MarkScheme findFirst
 */
export type MarkSchemeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * Filter, which MarkScheme to fetch.
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarkSchemes to fetch.
   */
  orderBy?: Prisma.MarkSchemeOrderByWithRelationInput | Prisma.MarkSchemeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarkSchemes.
   */
  cursor?: Prisma.MarkSchemeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarkSchemes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarkSchemes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarkSchemes.
   */
  distinct?: Prisma.MarkSchemeScalarFieldEnum | Prisma.MarkSchemeScalarFieldEnum[]
}

/**
 * MarkScheme findFirstOrThrow
 */
export type MarkSchemeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * Filter, which MarkScheme to fetch.
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarkSchemes to fetch.
   */
  orderBy?: Prisma.MarkSchemeOrderByWithRelationInput | Prisma.MarkSchemeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarkSchemes.
   */
  cursor?: Prisma.MarkSchemeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarkSchemes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarkSchemes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarkSchemes.
   */
  distinct?: Prisma.MarkSchemeScalarFieldEnum | Prisma.MarkSchemeScalarFieldEnum[]
}

/**
 * MarkScheme findMany
 */
export type MarkSchemeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * Filter, which MarkSchemes to fetch.
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarkSchemes to fetch.
   */
  orderBy?: Prisma.MarkSchemeOrderByWithRelationInput | Prisma.MarkSchemeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MarkSchemes.
   */
  cursor?: Prisma.MarkSchemeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarkSchemes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarkSchemes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarkSchemes.
   */
  distinct?: Prisma.MarkSchemeScalarFieldEnum | Prisma.MarkSchemeScalarFieldEnum[]
}

/**
 * MarkScheme create
 */
export type MarkSchemeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * The data needed to create a MarkScheme.
   */
  data: Prisma.XOR<Prisma.MarkSchemeCreateInput, Prisma.MarkSchemeUncheckedCreateInput>
}

/**
 * MarkScheme createMany
 */
export type MarkSchemeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MarkSchemes.
   */
  data: Prisma.MarkSchemeCreateManyInput | Prisma.MarkSchemeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarkScheme createManyAndReturn
 */
export type MarkSchemeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * The data used to create many MarkSchemes.
   */
  data: Prisma.MarkSchemeCreateManyInput | Prisma.MarkSchemeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MarkScheme update
 */
export type MarkSchemeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * The data needed to update a MarkScheme.
   */
  data: Prisma.XOR<Prisma.MarkSchemeUpdateInput, Prisma.MarkSchemeUncheckedUpdateInput>
  /**
   * Choose, which MarkScheme to update.
   */
  where: Prisma.MarkSchemeWhereUniqueInput
}

/**
 * MarkScheme updateMany
 */
export type MarkSchemeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MarkSchemes.
   */
  data: Prisma.XOR<Prisma.MarkSchemeUpdateManyMutationInput, Prisma.MarkSchemeUncheckedUpdateManyInput>
  /**
   * Filter which MarkSchemes to update
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * Limit how many MarkSchemes to update.
   */
  limit?: number
}

/**
 * MarkScheme updateManyAndReturn
 */
export type MarkSchemeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * The data used to update MarkSchemes.
   */
  data: Prisma.XOR<Prisma.MarkSchemeUpdateManyMutationInput, Prisma.MarkSchemeUncheckedUpdateManyInput>
  /**
   * Filter which MarkSchemes to update
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * Limit how many MarkSchemes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MarkScheme upsert
 */
export type MarkSchemeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * The filter to search for the MarkScheme to update in case it exists.
   */
  where: Prisma.MarkSchemeWhereUniqueInput
  /**
   * In case the MarkScheme found by the `where` argument doesn't exist, create a new MarkScheme with this data.
   */
  create: Prisma.XOR<Prisma.MarkSchemeCreateInput, Prisma.MarkSchemeUncheckedCreateInput>
  /**
   * In case the MarkScheme was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MarkSchemeUpdateInput, Prisma.MarkSchemeUncheckedUpdateInput>
}

/**
 * MarkScheme delete
 */
export type MarkSchemeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
  /**
   * Filter which MarkScheme to delete.
   */
  where: Prisma.MarkSchemeWhereUniqueInput
}

/**
 * MarkScheme deleteMany
 */
export type MarkSchemeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarkSchemes to delete
   */
  where?: Prisma.MarkSchemeWhereInput
  /**
   * Limit how many MarkSchemes to delete.
   */
  limit?: number
}

/**
 * MarkScheme without action
 */
export type MarkSchemeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarkScheme
   */
  select?: Prisma.MarkSchemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarkScheme
   */
  omit?: Prisma.MarkSchemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarkSchemeInclude<ExtArgs> | null
}
