
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Paper` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Paper
 * 
 */
export type PaperModel = runtime.Types.Result.DefaultSelection<Prisma.$PaperPayload>

export type AggregatePaper = {
  _count: PaperCountAggregateOutputType | null
  _avg: PaperAvgAggregateOutputType | null
  _sum: PaperSumAggregateOutputType | null
  _min: PaperMinAggregateOutputType | null
  _max: PaperMaxAggregateOutputType | null
}

export type PaperAvgAggregateOutputType = {
  id: number | null
  paper_number: number | null
}

export type PaperSumAggregateOutputType = {
  id: number | null
  paper_number: number | null
}

export type PaperMinAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  paper_id: string | null
  paper_code: string | null
  paper_number: number | null
  name: string | null
  subject: $Enums.Subject | null
  exam_board: $Enums.ExamBoard | null
  unit_name: string | null
  user_id: string | null
  course_id: string | null
  content: string | null
  status: $Enums.Status | null
}

export type PaperMaxAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  paper_id: string | null
  paper_code: string | null
  paper_number: number | null
  name: string | null
  subject: $Enums.Subject | null
  exam_board: $Enums.ExamBoard | null
  unit_name: string | null
  user_id: string | null
  course_id: string | null
  content: string | null
  status: $Enums.Status | null
}

export type PaperCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  paper_id: number
  paper_code: number
  paper_number: number
  name: number
  subject: number
  exam_board: number
  unit_name: number
  user_id: number
  course_id: number
  content: number
  status: number
  _all: number
}


export type PaperAvgAggregateInputType = {
  id?: true
  paper_number?: true
}

export type PaperSumAggregateInputType = {
  id?: true
  paper_number?: true
}

export type PaperMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  paper_id?: true
  paper_code?: true
  paper_number?: true
  name?: true
  subject?: true
  exam_board?: true
  unit_name?: true
  user_id?: true
  course_id?: true
  content?: true
  status?: true
}

export type PaperMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  paper_id?: true
  paper_code?: true
  paper_number?: true
  name?: true
  subject?: true
  exam_board?: true
  unit_name?: true
  user_id?: true
  course_id?: true
  content?: true
  status?: true
}

export type PaperCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  paper_id?: true
  paper_code?: true
  paper_number?: true
  name?: true
  subject?: true
  exam_board?: true
  unit_name?: true
  user_id?: true
  course_id?: true
  content?: true
  status?: true
  _all?: true
}

export type PaperAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Paper to aggregate.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Papers
  **/
  _count?: true | PaperCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PaperAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PaperSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaperMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaperMaxAggregateInputType
}

export type GetPaperAggregateType<T extends PaperAggregateArgs> = {
      [P in keyof T & keyof AggregatePaper]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaper[P]>
    : Prisma.GetScalarType<T[P], AggregatePaper[P]>
}




export type PaperGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaperWhereInput
  orderBy?: Prisma.PaperOrderByWithAggregationInput | Prisma.PaperOrderByWithAggregationInput[]
  by: Prisma.PaperScalarFieldEnum[] | Prisma.PaperScalarFieldEnum
  having?: Prisma.PaperScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaperCountAggregateInputType | true
  _avg?: PaperAvgAggregateInputType
  _sum?: PaperSumAggregateInputType
  _min?: PaperMinAggregateInputType
  _max?: PaperMaxAggregateInputType
}

export type PaperGroupByOutputType = {
  id: number
  created_at: Date
  updated_at: Date
  paper_id: string
  paper_code: string
  paper_number: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  user_id: string
  course_id: string
  content: string
  status: $Enums.Status
  _count: PaperCountAggregateOutputType | null
  _avg: PaperAvgAggregateOutputType | null
  _sum: PaperSumAggregateOutputType | null
  _min: PaperMinAggregateOutputType | null
  _max: PaperMaxAggregateOutputType | null
}

export type GetPaperGroupByPayload<T extends PaperGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaperGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaperGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaperGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaperGroupByOutputType[P]>
      }
    >
  >



export type PaperWhereInput = {
  AND?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  OR?: Prisma.PaperWhereInput[]
  NOT?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  id?: Prisma.IntFilter<"Paper"> | number
  created_at?: Prisma.DateTimeFilter<"Paper"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Paper"> | Date | string
  paper_id?: Prisma.StringFilter<"Paper"> | string
  paper_code?: Prisma.StringFilter<"Paper"> | string
  paper_number?: Prisma.IntFilter<"Paper"> | number
  name?: Prisma.StringFilter<"Paper"> | string
  subject?: Prisma.EnumSubjectFilter<"Paper"> | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFilter<"Paper"> | $Enums.ExamBoard
  unit_name?: Prisma.StringFilter<"Paper"> | string
  user_id?: Prisma.StringFilter<"Paper"> | string
  course_id?: Prisma.StringFilter<"Paper"> | string
  content?: Prisma.StringFilter<"Paper"> | string
  status?: Prisma.EnumStatusFilter<"Paper"> | $Enums.Status
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}

export type PaperOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  paper_code?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  exam_board?: Prisma.SortOrder
  unit_name?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  course_id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  status?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  course?: Prisma.CourseOrderByWithRelationInput
}

export type PaperWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  paper_id?: string
  AND?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  OR?: Prisma.PaperWhereInput[]
  NOT?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  created_at?: Prisma.DateTimeFilter<"Paper"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Paper"> | Date | string
  paper_code?: Prisma.StringFilter<"Paper"> | string
  paper_number?: Prisma.IntFilter<"Paper"> | number
  name?: Prisma.StringFilter<"Paper"> | string
  subject?: Prisma.EnumSubjectFilter<"Paper"> | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFilter<"Paper"> | $Enums.ExamBoard
  unit_name?: Prisma.StringFilter<"Paper"> | string
  user_id?: Prisma.StringFilter<"Paper"> | string
  course_id?: Prisma.StringFilter<"Paper"> | string
  content?: Prisma.StringFilter<"Paper"> | string
  status?: Prisma.EnumStatusFilter<"Paper"> | $Enums.Status
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}, "id" | "id" | "paper_id">

export type PaperOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  paper_code?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  exam_board?: Prisma.SortOrder
  unit_name?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  course_id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.PaperCountOrderByAggregateInput
  _avg?: Prisma.PaperAvgOrderByAggregateInput
  _max?: Prisma.PaperMaxOrderByAggregateInput
  _min?: Prisma.PaperMinOrderByAggregateInput
  _sum?: Prisma.PaperSumOrderByAggregateInput
}

export type PaperScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaperScalarWhereWithAggregatesInput | Prisma.PaperScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaperScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaperScalarWhereWithAggregatesInput | Prisma.PaperScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Paper"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Paper"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Paper"> | Date | string
  paper_id?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  paper_code?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  paper_number?: Prisma.IntWithAggregatesFilter<"Paper"> | number
  name?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  subject?: Prisma.EnumSubjectWithAggregatesFilter<"Paper"> | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardWithAggregatesFilter<"Paper"> | $Enums.ExamBoard
  unit_name?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  course_id?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  content?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  status?: Prisma.EnumStatusWithAggregatesFilter<"Paper"> | $Enums.Status
}

export type PaperCreateInput = {
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  content: string
  status?: $Enums.Status
  user: Prisma.UserCreateNestedOneWithoutPapersInput
  course: Prisma.CourseCreateNestedOneWithoutPapersInput
}

export type PaperUncheckedCreateInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  user_id: string
  course_id: string
  content: string
  status?: $Enums.Status
}

export type PaperUpdateInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  user?: Prisma.UserUpdateOneRequiredWithoutPapersNestedInput
  course?: Prisma.CourseUpdateOneRequiredWithoutPapersNestedInput
}

export type PaperUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  course_id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type PaperCreateManyInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  user_id: string
  course_id: string
  content: string
  status?: $Enums.Status
}

export type PaperUpdateManyMutationInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type PaperUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  course_id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type PaperListRelationFilter = {
  every?: Prisma.PaperWhereInput
  some?: Prisma.PaperWhereInput
  none?: Prisma.PaperWhereInput
}

export type PaperOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PaperCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  paper_code?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  exam_board?: Prisma.SortOrder
  unit_name?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  course_id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type PaperAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
}

export type PaperMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  paper_code?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  exam_board?: Prisma.SortOrder
  unit_name?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  course_id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type PaperMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  paper_code?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  exam_board?: Prisma.SortOrder
  unit_name?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  course_id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type PaperSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paper_number?: Prisma.SortOrder
}

export type PaperCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutCourseInput, Prisma.PaperUncheckedCreateWithoutCourseInput> | Prisma.PaperCreateWithoutCourseInput[] | Prisma.PaperUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutCourseInput | Prisma.PaperCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.PaperCreateManyCourseInputEnvelope
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
}

export type PaperUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutCourseInput, Prisma.PaperUncheckedCreateWithoutCourseInput> | Prisma.PaperCreateWithoutCourseInput[] | Prisma.PaperUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutCourseInput | Prisma.PaperCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.PaperCreateManyCourseInputEnvelope
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
}

export type PaperUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutCourseInput, Prisma.PaperUncheckedCreateWithoutCourseInput> | Prisma.PaperCreateWithoutCourseInput[] | Prisma.PaperUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutCourseInput | Prisma.PaperCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.PaperUpsertWithWhereUniqueWithoutCourseInput | Prisma.PaperUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.PaperCreateManyCourseInputEnvelope
  set?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  disconnect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  delete?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  update?: Prisma.PaperUpdateWithWhereUniqueWithoutCourseInput | Prisma.PaperUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.PaperUpdateManyWithWhereWithoutCourseInput | Prisma.PaperUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
}

export type PaperUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutCourseInput, Prisma.PaperUncheckedCreateWithoutCourseInput> | Prisma.PaperCreateWithoutCourseInput[] | Prisma.PaperUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutCourseInput | Prisma.PaperCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.PaperUpsertWithWhereUniqueWithoutCourseInput | Prisma.PaperUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.PaperCreateManyCourseInputEnvelope
  set?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  disconnect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  delete?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  update?: Prisma.PaperUpdateWithWhereUniqueWithoutCourseInput | Prisma.PaperUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.PaperUpdateManyWithWhereWithoutCourseInput | Prisma.PaperUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
}

export type EnumStatusFieldUpdateOperationsInput = {
  set?: $Enums.Status
}

export type PaperCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutUserInput, Prisma.PaperUncheckedCreateWithoutUserInput> | Prisma.PaperCreateWithoutUserInput[] | Prisma.PaperUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutUserInput | Prisma.PaperCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PaperCreateManyUserInputEnvelope
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
}

export type PaperUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutUserInput, Prisma.PaperUncheckedCreateWithoutUserInput> | Prisma.PaperCreateWithoutUserInput[] | Prisma.PaperUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutUserInput | Prisma.PaperCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PaperCreateManyUserInputEnvelope
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
}

export type PaperUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutUserInput, Prisma.PaperUncheckedCreateWithoutUserInput> | Prisma.PaperCreateWithoutUserInput[] | Prisma.PaperUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutUserInput | Prisma.PaperCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PaperUpsertWithWhereUniqueWithoutUserInput | Prisma.PaperUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PaperCreateManyUserInputEnvelope
  set?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  disconnect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  delete?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  update?: Prisma.PaperUpdateWithWhereUniqueWithoutUserInput | Prisma.PaperUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PaperUpdateManyWithWhereWithoutUserInput | Prisma.PaperUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
}

export type PaperUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutUserInput, Prisma.PaperUncheckedCreateWithoutUserInput> | Prisma.PaperCreateWithoutUserInput[] | Prisma.PaperUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutUserInput | Prisma.PaperCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PaperUpsertWithWhereUniqueWithoutUserInput | Prisma.PaperUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PaperCreateManyUserInputEnvelope
  set?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  disconnect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  delete?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  update?: Prisma.PaperUpdateWithWhereUniqueWithoutUserInput | Prisma.PaperUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PaperUpdateManyWithWhereWithoutUserInput | Prisma.PaperUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
}

export type PaperCreateWithoutCourseInput = {
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  content: string
  status?: $Enums.Status
  user: Prisma.UserCreateNestedOneWithoutPapersInput
}

export type PaperUncheckedCreateWithoutCourseInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  user_id: string
  content: string
  status?: $Enums.Status
}

export type PaperCreateOrConnectWithoutCourseInput = {
  where: Prisma.PaperWhereUniqueInput
  create: Prisma.XOR<Prisma.PaperCreateWithoutCourseInput, Prisma.PaperUncheckedCreateWithoutCourseInput>
}

export type PaperCreateManyCourseInputEnvelope = {
  data: Prisma.PaperCreateManyCourseInput | Prisma.PaperCreateManyCourseInput[]
  skipDuplicates?: boolean
}

export type PaperUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.PaperWhereUniqueInput
  update: Prisma.XOR<Prisma.PaperUpdateWithoutCourseInput, Prisma.PaperUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.PaperCreateWithoutCourseInput, Prisma.PaperUncheckedCreateWithoutCourseInput>
}

export type PaperUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.PaperWhereUniqueInput
  data: Prisma.XOR<Prisma.PaperUpdateWithoutCourseInput, Prisma.PaperUncheckedUpdateWithoutCourseInput>
}

export type PaperUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.PaperScalarWhereInput
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyWithoutCourseInput>
}

export type PaperScalarWhereInput = {
  AND?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
  OR?: Prisma.PaperScalarWhereInput[]
  NOT?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
  id?: Prisma.IntFilter<"Paper"> | number
  created_at?: Prisma.DateTimeFilter<"Paper"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Paper"> | Date | string
  paper_id?: Prisma.StringFilter<"Paper"> | string
  paper_code?: Prisma.StringFilter<"Paper"> | string
  paper_number?: Prisma.IntFilter<"Paper"> | number
  name?: Prisma.StringFilter<"Paper"> | string
  subject?: Prisma.EnumSubjectFilter<"Paper"> | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFilter<"Paper"> | $Enums.ExamBoard
  unit_name?: Prisma.StringFilter<"Paper"> | string
  user_id?: Prisma.StringFilter<"Paper"> | string
  course_id?: Prisma.StringFilter<"Paper"> | string
  content?: Prisma.StringFilter<"Paper"> | string
  status?: Prisma.EnumStatusFilter<"Paper"> | $Enums.Status
}

export type PaperCreateWithoutUserInput = {
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  content: string
  status?: $Enums.Status
  course: Prisma.CourseCreateNestedOneWithoutPapersInput
}

export type PaperUncheckedCreateWithoutUserInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  course_id: string
  content: string
  status?: $Enums.Status
}

export type PaperCreateOrConnectWithoutUserInput = {
  where: Prisma.PaperWhereUniqueInput
  create: Prisma.XOR<Prisma.PaperCreateWithoutUserInput, Prisma.PaperUncheckedCreateWithoutUserInput>
}

export type PaperCreateManyUserInputEnvelope = {
  data: Prisma.PaperCreateManyUserInput | Prisma.PaperCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PaperUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PaperWhereUniqueInput
  update: Prisma.XOR<Prisma.PaperUpdateWithoutUserInput, Prisma.PaperUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PaperCreateWithoutUserInput, Prisma.PaperUncheckedCreateWithoutUserInput>
}

export type PaperUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PaperWhereUniqueInput
  data: Prisma.XOR<Prisma.PaperUpdateWithoutUserInput, Prisma.PaperUncheckedUpdateWithoutUserInput>
}

export type PaperUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PaperScalarWhereInput
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyWithoutUserInput>
}

export type PaperCreateManyCourseInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  user_id: string
  content: string
  status?: $Enums.Status
}

export type PaperUpdateWithoutCourseInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  user?: Prisma.UserUpdateOneRequiredWithoutPapersNestedInput
}

export type PaperUncheckedUpdateWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type PaperUncheckedUpdateManyWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type PaperCreateManyUserInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  paper_code: string
  paper_number?: number
  name: string
  subject: $Enums.Subject
  exam_board: $Enums.ExamBoard
  unit_name: string
  course_id: string
  content: string
  status?: $Enums.Status
}

export type PaperUpdateWithoutUserInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  course?: Prisma.CourseUpdateOneRequiredWithoutPapersNestedInput
}

export type PaperUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  course_id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type PaperUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  paper_code?: Prisma.StringFieldUpdateOperationsInput | string
  paper_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.EnumSubjectFieldUpdateOperationsInput | $Enums.Subject
  exam_board?: Prisma.EnumExamBoardFieldUpdateOperationsInput | $Enums.ExamBoard
  unit_name?: Prisma.StringFieldUpdateOperationsInput | string
  course_id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}



export type PaperSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  paper_code?: boolean
  paper_number?: boolean
  name?: boolean
  subject?: boolean
  exam_board?: boolean
  unit_name?: boolean
  user_id?: boolean
  course_id?: boolean
  content?: boolean
  status?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paper"]>

export type PaperSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  paper_code?: boolean
  paper_number?: boolean
  name?: boolean
  subject?: boolean
  exam_board?: boolean
  unit_name?: boolean
  user_id?: boolean
  course_id?: boolean
  content?: boolean
  status?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paper"]>

export type PaperSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  paper_code?: boolean
  paper_number?: boolean
  name?: boolean
  subject?: boolean
  exam_board?: boolean
  unit_name?: boolean
  user_id?: boolean
  course_id?: boolean
  content?: boolean
  status?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paper"]>

export type PaperSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  paper_code?: boolean
  paper_number?: boolean
  name?: boolean
  subject?: boolean
  exam_board?: boolean
  unit_name?: boolean
  user_id?: boolean
  course_id?: boolean
  content?: boolean
  status?: boolean
}

export type PaperOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "paper_id" | "paper_code" | "paper_number" | "name" | "subject" | "exam_board" | "unit_name" | "user_id" | "course_id" | "content" | "status", ExtArgs["result"]["paper"]>
export type PaperInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}
export type PaperIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}
export type PaperIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  course?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}

export type $PaperPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Paper"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    course: Prisma.$CoursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    created_at: Date
    updated_at: Date
    paper_id: string
    paper_code: string
    paper_number: number
    name: string
    subject: $Enums.Subject
    exam_board: $Enums.ExamBoard
    unit_name: string
    user_id: string
    course_id: string
    content: string
    status: $Enums.Status
  }, ExtArgs["result"]["paper"]>
  composites: {}
}

export type PaperGetPayload<S extends boolean | null | undefined | PaperDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaperPayload, S>

export type PaperCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaperFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaperCountAggregateInputType | true
  }

export interface PaperDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Paper'], meta: { name: 'Paper' } }
  /**
   * Find zero or one Paper that matches the filter.
   * @param {PaperFindUniqueArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaperFindUniqueArgs>(args: Prisma.SelectSubset<T, PaperFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Paper that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaperFindUniqueOrThrowArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaperFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaperFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Paper that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperFindFirstArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaperFindFirstArgs>(args?: Prisma.SelectSubset<T, PaperFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Paper that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperFindFirstOrThrowArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaperFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaperFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Papers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Papers
   * const papers = await prisma.paper.findMany()
   * 
   * // Get first 10 Papers
   * const papers = await prisma.paper.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paperWithIdOnly = await prisma.paper.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaperFindManyArgs>(args?: Prisma.SelectSubset<T, PaperFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Paper.
   * @param {PaperCreateArgs} args - Arguments to create a Paper.
   * @example
   * // Create one Paper
   * const Paper = await prisma.paper.create({
   *   data: {
   *     // ... data to create a Paper
   *   }
   * })
   * 
   */
  create<T extends PaperCreateArgs>(args: Prisma.SelectSubset<T, PaperCreateArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Papers.
   * @param {PaperCreateManyArgs} args - Arguments to create many Papers.
   * @example
   * // Create many Papers
   * const paper = await prisma.paper.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaperCreateManyArgs>(args?: Prisma.SelectSubset<T, PaperCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Papers and returns the data saved in the database.
   * @param {PaperCreateManyAndReturnArgs} args - Arguments to create many Papers.
   * @example
   * // Create many Papers
   * const paper = await prisma.paper.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Papers and only return the `id`
   * const paperWithIdOnly = await prisma.paper.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PaperCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PaperCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Paper.
   * @param {PaperDeleteArgs} args - Arguments to delete one Paper.
   * @example
   * // Delete one Paper
   * const Paper = await prisma.paper.delete({
   *   where: {
   *     // ... filter to delete one Paper
   *   }
   * })
   * 
   */
  delete<T extends PaperDeleteArgs>(args: Prisma.SelectSubset<T, PaperDeleteArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Paper.
   * @param {PaperUpdateArgs} args - Arguments to update one Paper.
   * @example
   * // Update one Paper
   * const paper = await prisma.paper.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaperUpdateArgs>(args: Prisma.SelectSubset<T, PaperUpdateArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Papers.
   * @param {PaperDeleteManyArgs} args - Arguments to filter Papers to delete.
   * @example
   * // Delete a few Papers
   * const { count } = await prisma.paper.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaperDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaperDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Papers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Papers
   * const paper = await prisma.paper.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaperUpdateManyArgs>(args: Prisma.SelectSubset<T, PaperUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Papers and returns the data updated in the database.
   * @param {PaperUpdateManyAndReturnArgs} args - Arguments to update many Papers.
   * @example
   * // Update many Papers
   * const paper = await prisma.paper.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Papers and only return the `id`
   * const paperWithIdOnly = await prisma.paper.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PaperUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PaperUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Paper.
   * @param {PaperUpsertArgs} args - Arguments to update or create a Paper.
   * @example
   * // Update or create a Paper
   * const paper = await prisma.paper.upsert({
   *   create: {
   *     // ... data to create a Paper
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Paper we want to update
   *   }
   * })
   */
  upsert<T extends PaperUpsertArgs>(args: Prisma.SelectSubset<T, PaperUpsertArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Papers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperCountArgs} args - Arguments to filter Papers to count.
   * @example
   * // Count the number of Papers
   * const count = await prisma.paper.count({
   *   where: {
   *     // ... the filter for the Papers we want to count
   *   }
   * })
  **/
  count<T extends PaperCountArgs>(
    args?: Prisma.Subset<T, PaperCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaperCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Paper.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaperAggregateArgs>(args: Prisma.Subset<T, PaperAggregateArgs>): Prisma.PrismaPromise<GetPaperAggregateType<T>>

  /**
   * Group by Paper.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaperGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaperGroupByArgs['orderBy'] }
      : { orderBy?: PaperGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaperGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaperGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Paper model
 */
readonly fields: PaperFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Paper.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaperClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  course<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Paper model
 */
export interface PaperFieldRefs {
  readonly id: Prisma.FieldRef<"Paper", 'Int'>
  readonly created_at: Prisma.FieldRef<"Paper", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Paper", 'DateTime'>
  readonly paper_id: Prisma.FieldRef<"Paper", 'String'>
  readonly paper_code: Prisma.FieldRef<"Paper", 'String'>
  readonly paper_number: Prisma.FieldRef<"Paper", 'Int'>
  readonly name: Prisma.FieldRef<"Paper", 'String'>
  readonly subject: Prisma.FieldRef<"Paper", 'Subject'>
  readonly exam_board: Prisma.FieldRef<"Paper", 'ExamBoard'>
  readonly unit_name: Prisma.FieldRef<"Paper", 'String'>
  readonly user_id: Prisma.FieldRef<"Paper", 'String'>
  readonly course_id: Prisma.FieldRef<"Paper", 'String'>
  readonly content: Prisma.FieldRef<"Paper", 'String'>
  readonly status: Prisma.FieldRef<"Paper", 'Status'>
}
    

// Custom InputTypes
/**
 * Paper findUnique
 */
export type PaperFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper findUniqueOrThrow
 */
export type PaperFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper findFirst
 */
export type PaperFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Papers.
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Papers.
   */
  distinct?: Prisma.PaperScalarFieldEnum | Prisma.PaperScalarFieldEnum[]
}

/**
 * Paper findFirstOrThrow
 */
export type PaperFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Papers.
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Papers.
   */
  distinct?: Prisma.PaperScalarFieldEnum | Prisma.PaperScalarFieldEnum[]
}

/**
 * Paper findMany
 */
export type PaperFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Papers to fetch.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Papers.
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Papers.
   */
  distinct?: Prisma.PaperScalarFieldEnum | Prisma.PaperScalarFieldEnum[]
}

/**
 * Paper create
 */
export type PaperCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * The data needed to create a Paper.
   */
  data: Prisma.XOR<Prisma.PaperCreateInput, Prisma.PaperUncheckedCreateInput>
}

/**
 * Paper createMany
 */
export type PaperCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Papers.
   */
  data: Prisma.PaperCreateManyInput | Prisma.PaperCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Paper createManyAndReturn
 */
export type PaperCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * The data used to create many Papers.
   */
  data: Prisma.PaperCreateManyInput | Prisma.PaperCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Paper update
 */
export type PaperUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * The data needed to update a Paper.
   */
  data: Prisma.XOR<Prisma.PaperUpdateInput, Prisma.PaperUncheckedUpdateInput>
  /**
   * Choose, which Paper to update.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper updateMany
 */
export type PaperUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Papers.
   */
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyInput>
  /**
   * Filter which Papers to update
   */
  where?: Prisma.PaperWhereInput
  /**
   * Limit how many Papers to update.
   */
  limit?: number
}

/**
 * Paper updateManyAndReturn
 */
export type PaperUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * The data used to update Papers.
   */
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyInput>
  /**
   * Filter which Papers to update
   */
  where?: Prisma.PaperWhereInput
  /**
   * Limit how many Papers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Paper upsert
 */
export type PaperUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * The filter to search for the Paper to update in case it exists.
   */
  where: Prisma.PaperWhereUniqueInput
  /**
   * In case the Paper found by the `where` argument doesn't exist, create a new Paper with this data.
   */
  create: Prisma.XOR<Prisma.PaperCreateInput, Prisma.PaperUncheckedCreateInput>
  /**
   * In case the Paper was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaperUpdateInput, Prisma.PaperUncheckedUpdateInput>
}

/**
 * Paper delete
 */
export type PaperDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter which Paper to delete.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper deleteMany
 */
export type PaperDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Papers to delete
   */
  where?: Prisma.PaperWhereInput
  /**
   * Limit how many Papers to delete.
   */
  limit?: number
}

/**
 * Paper without action
 */
export type PaperDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
}
