
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PaperRating` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PaperRating
 * 
 */
export type PaperRatingModel = runtime.Types.Result.DefaultSelection<Prisma.$PaperRatingPayload>

export type AggregatePaperRating = {
  _count: PaperRatingCountAggregateOutputType | null
  _avg: PaperRatingAvgAggregateOutputType | null
  _sum: PaperRatingSumAggregateOutputType | null
  _min: PaperRatingMinAggregateOutputType | null
  _max: PaperRatingMaxAggregateOutputType | null
}

export type PaperRatingAvgAggregateOutputType = {
  id: number | null
  stars: number | null
}

export type PaperRatingSumAggregateOutputType = {
  id: number | null
  stars: number | null
}

export type PaperRatingMinAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  paper_id: string | null
  stars: number | null
  comment: string | null
}

export type PaperRatingMaxAggregateOutputType = {
  id: number | null
  created_at: Date | null
  updated_at: Date | null
  paper_id: string | null
  stars: number | null
  comment: string | null
}

export type PaperRatingCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  paper_id: number
  stars: number
  comment: number
  dimensions: number
  _all: number
}


export type PaperRatingAvgAggregateInputType = {
  id?: true
  stars?: true
}

export type PaperRatingSumAggregateInputType = {
  id?: true
  stars?: true
}

export type PaperRatingMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  paper_id?: true
  stars?: true
  comment?: true
}

export type PaperRatingMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  paper_id?: true
  stars?: true
  comment?: true
}

export type PaperRatingCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  paper_id?: true
  stars?: true
  comment?: true
  dimensions?: true
  _all?: true
}

export type PaperRatingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaperRating to aggregate.
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaperRatings to fetch.
   */
  orderBy?: Prisma.PaperRatingOrderByWithRelationInput | Prisma.PaperRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaperRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaperRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaperRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PaperRatings
  **/
  _count?: true | PaperRatingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PaperRatingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PaperRatingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaperRatingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaperRatingMaxAggregateInputType
}

export type GetPaperRatingAggregateType<T extends PaperRatingAggregateArgs> = {
      [P in keyof T & keyof AggregatePaperRating]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaperRating[P]>
    : Prisma.GetScalarType<T[P], AggregatePaperRating[P]>
}




export type PaperRatingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaperRatingWhereInput
  orderBy?: Prisma.PaperRatingOrderByWithAggregationInput | Prisma.PaperRatingOrderByWithAggregationInput[]
  by: Prisma.PaperRatingScalarFieldEnum[] | Prisma.PaperRatingScalarFieldEnum
  having?: Prisma.PaperRatingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaperRatingCountAggregateInputType | true
  _avg?: PaperRatingAvgAggregateInputType
  _sum?: PaperRatingSumAggregateInputType
  _min?: PaperRatingMinAggregateInputType
  _max?: PaperRatingMaxAggregateInputType
}

export type PaperRatingGroupByOutputType = {
  id: number
  created_at: Date
  updated_at: Date
  paper_id: string
  stars: number
  comment: string | null
  dimensions: runtime.JsonValue | null
  _count: PaperRatingCountAggregateOutputType | null
  _avg: PaperRatingAvgAggregateOutputType | null
  _sum: PaperRatingSumAggregateOutputType | null
  _min: PaperRatingMinAggregateOutputType | null
  _max: PaperRatingMaxAggregateOutputType | null
}

export type GetPaperRatingGroupByPayload<T extends PaperRatingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaperRatingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaperRatingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaperRatingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaperRatingGroupByOutputType[P]>
      }
    >
  >



export type PaperRatingWhereInput = {
  AND?: Prisma.PaperRatingWhereInput | Prisma.PaperRatingWhereInput[]
  OR?: Prisma.PaperRatingWhereInput[]
  NOT?: Prisma.PaperRatingWhereInput | Prisma.PaperRatingWhereInput[]
  id?: Prisma.IntFilter<"PaperRating"> | number
  created_at?: Prisma.DateTimeFilter<"PaperRating"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PaperRating"> | Date | string
  paper_id?: Prisma.StringFilter<"PaperRating"> | string
  stars?: Prisma.IntFilter<"PaperRating"> | number
  comment?: Prisma.StringNullableFilter<"PaperRating"> | string | null
  dimensions?: Prisma.JsonNullableFilter<"PaperRating">
  paper?: Prisma.XOR<Prisma.PaperScalarRelationFilter, Prisma.PaperWhereInput>
}

export type PaperRatingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
  comment?: Prisma.SortOrderInput | Prisma.SortOrder
  dimensions?: Prisma.SortOrderInput | Prisma.SortOrder
  paper?: Prisma.PaperOrderByWithRelationInput
}

export type PaperRatingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  paper_id?: string
  AND?: Prisma.PaperRatingWhereInput | Prisma.PaperRatingWhereInput[]
  OR?: Prisma.PaperRatingWhereInput[]
  NOT?: Prisma.PaperRatingWhereInput | Prisma.PaperRatingWhereInput[]
  created_at?: Prisma.DateTimeFilter<"PaperRating"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PaperRating"> | Date | string
  stars?: Prisma.IntFilter<"PaperRating"> | number
  comment?: Prisma.StringNullableFilter<"PaperRating"> | string | null
  dimensions?: Prisma.JsonNullableFilter<"PaperRating">
  paper?: Prisma.XOR<Prisma.PaperScalarRelationFilter, Prisma.PaperWhereInput>
}, "id" | "id" | "paper_id">

export type PaperRatingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
  comment?: Prisma.SortOrderInput | Prisma.SortOrder
  dimensions?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PaperRatingCountOrderByAggregateInput
  _avg?: Prisma.PaperRatingAvgOrderByAggregateInput
  _max?: Prisma.PaperRatingMaxOrderByAggregateInput
  _min?: Prisma.PaperRatingMinOrderByAggregateInput
  _sum?: Prisma.PaperRatingSumOrderByAggregateInput
}

export type PaperRatingScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaperRatingScalarWhereWithAggregatesInput | Prisma.PaperRatingScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaperRatingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaperRatingScalarWhereWithAggregatesInput | Prisma.PaperRatingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PaperRating"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"PaperRating"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"PaperRating"> | Date | string
  paper_id?: Prisma.StringWithAggregatesFilter<"PaperRating"> | string
  stars?: Prisma.IntWithAggregatesFilter<"PaperRating"> | number
  comment?: Prisma.StringNullableWithAggregatesFilter<"PaperRating"> | string | null
  dimensions?: Prisma.JsonNullableWithAggregatesFilter<"PaperRating">
}

export type PaperRatingCreateInput = {
  created_at?: Date | string
  updated_at?: Date | string
  stars: number
  comment?: string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paper: Prisma.PaperCreateNestedOneWithoutPaperRatingInput
}

export type PaperRatingUncheckedCreateInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  stars: number
  comment?: string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingUpdateInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stars?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paper?: Prisma.PaperUpdateOneRequiredWithoutPaperRatingNestedInput
}

export type PaperRatingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  stars?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingCreateManyInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  paper_id: string
  stars: number
  comment?: string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingUpdateManyMutationInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stars?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper_id?: Prisma.StringFieldUpdateOperationsInput | string
  stars?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  dimensions?: Prisma.SortOrder
}

export type PaperRatingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
}

export type PaperRatingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
  comment?: Prisma.SortOrder
}

export type PaperRatingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  paper_id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
  comment?: Prisma.SortOrder
}

export type PaperRatingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stars?: Prisma.SortOrder
}

export type PaperRatingNullableScalarRelationFilter = {
  is?: Prisma.PaperRatingWhereInput | null
  isNot?: Prisma.PaperRatingWhereInput | null
}

export type PaperRatingCreateNestedOneWithoutPaperInput = {
  create?: Prisma.XOR<Prisma.PaperRatingCreateWithoutPaperInput, Prisma.PaperRatingUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.PaperRatingCreateOrConnectWithoutPaperInput
  connect?: Prisma.PaperRatingWhereUniqueInput
}

export type PaperRatingUncheckedCreateNestedOneWithoutPaperInput = {
  create?: Prisma.XOR<Prisma.PaperRatingCreateWithoutPaperInput, Prisma.PaperRatingUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.PaperRatingCreateOrConnectWithoutPaperInput
  connect?: Prisma.PaperRatingWhereUniqueInput
}

export type PaperRatingUpdateOneWithoutPaperNestedInput = {
  create?: Prisma.XOR<Prisma.PaperRatingCreateWithoutPaperInput, Prisma.PaperRatingUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.PaperRatingCreateOrConnectWithoutPaperInput
  upsert?: Prisma.PaperRatingUpsertWithoutPaperInput
  disconnect?: Prisma.PaperRatingWhereInput | boolean
  delete?: Prisma.PaperRatingWhereInput | boolean
  connect?: Prisma.PaperRatingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PaperRatingUpdateToOneWithWhereWithoutPaperInput, Prisma.PaperRatingUpdateWithoutPaperInput>, Prisma.PaperRatingUncheckedUpdateWithoutPaperInput>
}

export type PaperRatingUncheckedUpdateOneWithoutPaperNestedInput = {
  create?: Prisma.XOR<Prisma.PaperRatingCreateWithoutPaperInput, Prisma.PaperRatingUncheckedCreateWithoutPaperInput>
  connectOrCreate?: Prisma.PaperRatingCreateOrConnectWithoutPaperInput
  upsert?: Prisma.PaperRatingUpsertWithoutPaperInput
  disconnect?: Prisma.PaperRatingWhereInput | boolean
  delete?: Prisma.PaperRatingWhereInput | boolean
  connect?: Prisma.PaperRatingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PaperRatingUpdateToOneWithWhereWithoutPaperInput, Prisma.PaperRatingUpdateWithoutPaperInput>, Prisma.PaperRatingUncheckedUpdateWithoutPaperInput>
}

export type PaperRatingCreateWithoutPaperInput = {
  created_at?: Date | string
  updated_at?: Date | string
  stars: number
  comment?: string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingUncheckedCreateWithoutPaperInput = {
  id?: number
  created_at?: Date | string
  updated_at?: Date | string
  stars: number
  comment?: string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingCreateOrConnectWithoutPaperInput = {
  where: Prisma.PaperRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.PaperRatingCreateWithoutPaperInput, Prisma.PaperRatingUncheckedCreateWithoutPaperInput>
}

export type PaperRatingUpsertWithoutPaperInput = {
  update: Prisma.XOR<Prisma.PaperRatingUpdateWithoutPaperInput, Prisma.PaperRatingUncheckedUpdateWithoutPaperInput>
  create: Prisma.XOR<Prisma.PaperRatingCreateWithoutPaperInput, Prisma.PaperRatingUncheckedCreateWithoutPaperInput>
  where?: Prisma.PaperRatingWhereInput
}

export type PaperRatingUpdateToOneWithWhereWithoutPaperInput = {
  where?: Prisma.PaperRatingWhereInput
  data: Prisma.XOR<Prisma.PaperRatingUpdateWithoutPaperInput, Prisma.PaperRatingUncheckedUpdateWithoutPaperInput>
}

export type PaperRatingUpdateWithoutPaperInput = {
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stars?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type PaperRatingUncheckedUpdateWithoutPaperInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stars?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dimensions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}



export type PaperRatingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  stars?: boolean
  comment?: boolean
  dimensions?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paperRating"]>

export type PaperRatingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  stars?: boolean
  comment?: boolean
  dimensions?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paperRating"]>

export type PaperRatingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  stars?: boolean
  comment?: boolean
  dimensions?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paperRating"]>

export type PaperRatingSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  paper_id?: boolean
  stars?: boolean
  comment?: boolean
  dimensions?: boolean
}

export type PaperRatingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "paper_id" | "stars" | "comment" | "dimensions", ExtArgs["result"]["paperRating"]>
export type PaperRatingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}
export type PaperRatingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}
export type PaperRatingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}

export type $PaperRatingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PaperRating"
  objects: {
    paper: Prisma.$PaperPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    created_at: Date
    updated_at: Date
    paper_id: string
    stars: number
    comment: string | null
    dimensions: runtime.JsonValue | null
  }, ExtArgs["result"]["paperRating"]>
  composites: {}
}

export type PaperRatingGetPayload<S extends boolean | null | undefined | PaperRatingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload, S>

export type PaperRatingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaperRatingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaperRatingCountAggregateInputType | true
  }

export interface PaperRatingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PaperRating'], meta: { name: 'PaperRating' } }
  /**
   * Find zero or one PaperRating that matches the filter.
   * @param {PaperRatingFindUniqueArgs} args - Arguments to find a PaperRating
   * @example
   * // Get one PaperRating
   * const paperRating = await prisma.paperRating.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaperRatingFindUniqueArgs>(args: Prisma.SelectSubset<T, PaperRatingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PaperRating that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaperRatingFindUniqueOrThrowArgs} args - Arguments to find a PaperRating
   * @example
   * // Get one PaperRating
   * const paperRating = await prisma.paperRating.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaperRatingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaperRatingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaperRating that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingFindFirstArgs} args - Arguments to find a PaperRating
   * @example
   * // Get one PaperRating
   * const paperRating = await prisma.paperRating.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaperRatingFindFirstArgs>(args?: Prisma.SelectSubset<T, PaperRatingFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaperRating that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingFindFirstOrThrowArgs} args - Arguments to find a PaperRating
   * @example
   * // Get one PaperRating
   * const paperRating = await prisma.paperRating.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaperRatingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaperRatingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PaperRatings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PaperRatings
   * const paperRatings = await prisma.paperRating.findMany()
   * 
   * // Get first 10 PaperRatings
   * const paperRatings = await prisma.paperRating.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paperRatingWithIdOnly = await prisma.paperRating.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaperRatingFindManyArgs>(args?: Prisma.SelectSubset<T, PaperRatingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PaperRating.
   * @param {PaperRatingCreateArgs} args - Arguments to create a PaperRating.
   * @example
   * // Create one PaperRating
   * const PaperRating = await prisma.paperRating.create({
   *   data: {
   *     // ... data to create a PaperRating
   *   }
   * })
   * 
   */
  create<T extends PaperRatingCreateArgs>(args: Prisma.SelectSubset<T, PaperRatingCreateArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PaperRatings.
   * @param {PaperRatingCreateManyArgs} args - Arguments to create many PaperRatings.
   * @example
   * // Create many PaperRatings
   * const paperRating = await prisma.paperRating.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaperRatingCreateManyArgs>(args?: Prisma.SelectSubset<T, PaperRatingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PaperRatings and returns the data saved in the database.
   * @param {PaperRatingCreateManyAndReturnArgs} args - Arguments to create many PaperRatings.
   * @example
   * // Create many PaperRatings
   * const paperRating = await prisma.paperRating.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PaperRatings and only return the `id`
   * const paperRatingWithIdOnly = await prisma.paperRating.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PaperRatingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PaperRatingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PaperRating.
   * @param {PaperRatingDeleteArgs} args - Arguments to delete one PaperRating.
   * @example
   * // Delete one PaperRating
   * const PaperRating = await prisma.paperRating.delete({
   *   where: {
   *     // ... filter to delete one PaperRating
   *   }
   * })
   * 
   */
  delete<T extends PaperRatingDeleteArgs>(args: Prisma.SelectSubset<T, PaperRatingDeleteArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PaperRating.
   * @param {PaperRatingUpdateArgs} args - Arguments to update one PaperRating.
   * @example
   * // Update one PaperRating
   * const paperRating = await prisma.paperRating.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaperRatingUpdateArgs>(args: Prisma.SelectSubset<T, PaperRatingUpdateArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PaperRatings.
   * @param {PaperRatingDeleteManyArgs} args - Arguments to filter PaperRatings to delete.
   * @example
   * // Delete a few PaperRatings
   * const { count } = await prisma.paperRating.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaperRatingDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaperRatingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaperRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PaperRatings
   * const paperRating = await prisma.paperRating.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaperRatingUpdateManyArgs>(args: Prisma.SelectSubset<T, PaperRatingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaperRatings and returns the data updated in the database.
   * @param {PaperRatingUpdateManyAndReturnArgs} args - Arguments to update many PaperRatings.
   * @example
   * // Update many PaperRatings
   * const paperRating = await prisma.paperRating.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PaperRatings and only return the `id`
   * const paperRatingWithIdOnly = await prisma.paperRating.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PaperRatingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PaperRatingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PaperRating.
   * @param {PaperRatingUpsertArgs} args - Arguments to update or create a PaperRating.
   * @example
   * // Update or create a PaperRating
   * const paperRating = await prisma.paperRating.upsert({
   *   create: {
   *     // ... data to create a PaperRating
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PaperRating we want to update
   *   }
   * })
   */
  upsert<T extends PaperRatingUpsertArgs>(args: Prisma.SelectSubset<T, PaperRatingUpsertArgs<ExtArgs>>): Prisma.Prisma__PaperRatingClient<runtime.Types.Result.GetResult<Prisma.$PaperRatingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PaperRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingCountArgs} args - Arguments to filter PaperRatings to count.
   * @example
   * // Count the number of PaperRatings
   * const count = await prisma.paperRating.count({
   *   where: {
   *     // ... the filter for the PaperRatings we want to count
   *   }
   * })
  **/
  count<T extends PaperRatingCountArgs>(
    args?: Prisma.Subset<T, PaperRatingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaperRatingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PaperRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaperRatingAggregateArgs>(args: Prisma.Subset<T, PaperRatingAggregateArgs>): Prisma.PrismaPromise<GetPaperRatingAggregateType<T>>

  /**
   * Group by PaperRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperRatingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaperRatingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaperRatingGroupByArgs['orderBy'] }
      : { orderBy?: PaperRatingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaperRatingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaperRatingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PaperRating model
 */
readonly fields: PaperRatingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PaperRating.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaperRatingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  paper<T extends Prisma.PaperDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PaperDefaultArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PaperRating model
 */
export interface PaperRatingFieldRefs {
  readonly id: Prisma.FieldRef<"PaperRating", 'Int'>
  readonly created_at: Prisma.FieldRef<"PaperRating", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"PaperRating", 'DateTime'>
  readonly paper_id: Prisma.FieldRef<"PaperRating", 'String'>
  readonly stars: Prisma.FieldRef<"PaperRating", 'Int'>
  readonly comment: Prisma.FieldRef<"PaperRating", 'String'>
  readonly dimensions: Prisma.FieldRef<"PaperRating", 'Json'>
}
    

// Custom InputTypes
/**
 * PaperRating findUnique
 */
export type PaperRatingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * Filter, which PaperRating to fetch.
   */
  where: Prisma.PaperRatingWhereUniqueInput
}

/**
 * PaperRating findUniqueOrThrow
 */
export type PaperRatingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * Filter, which PaperRating to fetch.
   */
  where: Prisma.PaperRatingWhereUniqueInput
}

/**
 * PaperRating findFirst
 */
export type PaperRatingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * Filter, which PaperRating to fetch.
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaperRatings to fetch.
   */
  orderBy?: Prisma.PaperRatingOrderByWithRelationInput | Prisma.PaperRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaperRatings.
   */
  cursor?: Prisma.PaperRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaperRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaperRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaperRatings.
   */
  distinct?: Prisma.PaperRatingScalarFieldEnum | Prisma.PaperRatingScalarFieldEnum[]
}

/**
 * PaperRating findFirstOrThrow
 */
export type PaperRatingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * Filter, which PaperRating to fetch.
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaperRatings to fetch.
   */
  orderBy?: Prisma.PaperRatingOrderByWithRelationInput | Prisma.PaperRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaperRatings.
   */
  cursor?: Prisma.PaperRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaperRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaperRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaperRatings.
   */
  distinct?: Prisma.PaperRatingScalarFieldEnum | Prisma.PaperRatingScalarFieldEnum[]
}

/**
 * PaperRating findMany
 */
export type PaperRatingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * Filter, which PaperRatings to fetch.
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaperRatings to fetch.
   */
  orderBy?: Prisma.PaperRatingOrderByWithRelationInput | Prisma.PaperRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PaperRatings.
   */
  cursor?: Prisma.PaperRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaperRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaperRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaperRatings.
   */
  distinct?: Prisma.PaperRatingScalarFieldEnum | Prisma.PaperRatingScalarFieldEnum[]
}

/**
 * PaperRating create
 */
export type PaperRatingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * The data needed to create a PaperRating.
   */
  data: Prisma.XOR<Prisma.PaperRatingCreateInput, Prisma.PaperRatingUncheckedCreateInput>
}

/**
 * PaperRating createMany
 */
export type PaperRatingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PaperRatings.
   */
  data: Prisma.PaperRatingCreateManyInput | Prisma.PaperRatingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PaperRating createManyAndReturn
 */
export type PaperRatingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * The data used to create many PaperRatings.
   */
  data: Prisma.PaperRatingCreateManyInput | Prisma.PaperRatingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PaperRating update
 */
export type PaperRatingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * The data needed to update a PaperRating.
   */
  data: Prisma.XOR<Prisma.PaperRatingUpdateInput, Prisma.PaperRatingUncheckedUpdateInput>
  /**
   * Choose, which PaperRating to update.
   */
  where: Prisma.PaperRatingWhereUniqueInput
}

/**
 * PaperRating updateMany
 */
export type PaperRatingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PaperRatings.
   */
  data: Prisma.XOR<Prisma.PaperRatingUpdateManyMutationInput, Prisma.PaperRatingUncheckedUpdateManyInput>
  /**
   * Filter which PaperRatings to update
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * Limit how many PaperRatings to update.
   */
  limit?: number
}

/**
 * PaperRating updateManyAndReturn
 */
export type PaperRatingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * The data used to update PaperRatings.
   */
  data: Prisma.XOR<Prisma.PaperRatingUpdateManyMutationInput, Prisma.PaperRatingUncheckedUpdateManyInput>
  /**
   * Filter which PaperRatings to update
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * Limit how many PaperRatings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PaperRating upsert
 */
export type PaperRatingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * The filter to search for the PaperRating to update in case it exists.
   */
  where: Prisma.PaperRatingWhereUniqueInput
  /**
   * In case the PaperRating found by the `where` argument doesn't exist, create a new PaperRating with this data.
   */
  create: Prisma.XOR<Prisma.PaperRatingCreateInput, Prisma.PaperRatingUncheckedCreateInput>
  /**
   * In case the PaperRating was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaperRatingUpdateInput, Prisma.PaperRatingUncheckedUpdateInput>
}

/**
 * PaperRating delete
 */
export type PaperRatingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
  /**
   * Filter which PaperRating to delete.
   */
  where: Prisma.PaperRatingWhereUniqueInput
}

/**
 * PaperRating deleteMany
 */
export type PaperRatingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaperRatings to delete
   */
  where?: Prisma.PaperRatingWhereInput
  /**
   * Limit how many PaperRatings to delete.
   */
  limit?: number
}

/**
 * PaperRating without action
 */
export type PaperRatingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperRating
   */
  select?: Prisma.PaperRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaperRating
   */
  omit?: Prisma.PaperRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperRatingInclude<ExtArgs> | null
}
