
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StripeEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model StripeEvent
 * 
 */
export type StripeEventModel = runtime.Types.Result.DefaultSelection<Prisma.$StripeEventPayload>

export type AggregateStripeEvent = {
  _count: StripeEventCountAggregateOutputType | null
  _avg: StripeEventAvgAggregateOutputType | null
  _sum: StripeEventSumAggregateOutputType | null
  _min: StripeEventMinAggregateOutputType | null
  _max: StripeEventMaxAggregateOutputType | null
}

export type StripeEventAvgAggregateOutputType = {
  pending_webhooks: number | null
}

export type StripeEventSumAggregateOutputType = {
  pending_webhooks: number | null
}

export type StripeEventMinAggregateOutputType = {
  id: string | null
  api_version: string | null
  type: string | null
  object: string | null
  account: string | null
  created: Date | null
  livemode: boolean | null
  pending_webhooks: number | null
}

export type StripeEventMaxAggregateOutputType = {
  id: string | null
  api_version: string | null
  type: string | null
  object: string | null
  account: string | null
  created: Date | null
  livemode: boolean | null
  pending_webhooks: number | null
}

export type StripeEventCountAggregateOutputType = {
  id: number
  api_version: number
  data: number
  request: number
  type: number
  object: number
  account: number
  created: number
  livemode: number
  pending_webhooks: number
  _all: number
}


export type StripeEventAvgAggregateInputType = {
  pending_webhooks?: true
}

export type StripeEventSumAggregateInputType = {
  pending_webhooks?: true
}

export type StripeEventMinAggregateInputType = {
  id?: true
  api_version?: true
  type?: true
  object?: true
  account?: true
  created?: true
  livemode?: true
  pending_webhooks?: true
}

export type StripeEventMaxAggregateInputType = {
  id?: true
  api_version?: true
  type?: true
  object?: true
  account?: true
  created?: true
  livemode?: true
  pending_webhooks?: true
}

export type StripeEventCountAggregateInputType = {
  id?: true
  api_version?: true
  data?: true
  request?: true
  type?: true
  object?: true
  account?: true
  created?: true
  livemode?: true
  pending_webhooks?: true
  _all?: true
}

export type StripeEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StripeEvent to aggregate.
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StripeEvents to fetch.
   */
  orderBy?: Prisma.StripeEventOrderByWithRelationInput | Prisma.StripeEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StripeEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StripeEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StripeEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StripeEvents
  **/
  _count?: true | StripeEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StripeEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StripeEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StripeEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StripeEventMaxAggregateInputType
}

export type GetStripeEventAggregateType<T extends StripeEventAggregateArgs> = {
      [P in keyof T & keyof AggregateStripeEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStripeEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateStripeEvent[P]>
}




export type StripeEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StripeEventWhereInput
  orderBy?: Prisma.StripeEventOrderByWithAggregationInput | Prisma.StripeEventOrderByWithAggregationInput[]
  by: Prisma.StripeEventScalarFieldEnum[] | Prisma.StripeEventScalarFieldEnum
  having?: Prisma.StripeEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StripeEventCountAggregateInputType | true
  _avg?: StripeEventAvgAggregateInputType
  _sum?: StripeEventSumAggregateInputType
  _min?: StripeEventMinAggregateInputType
  _max?: StripeEventMaxAggregateInputType
}

export type StripeEventGroupByOutputType = {
  id: string
  api_version: string | null
  data: runtime.JsonValue
  request: runtime.JsonValue | null
  type: string
  object: string
  account: string | null
  created: Date
  livemode: boolean
  pending_webhooks: number
  _count: StripeEventCountAggregateOutputType | null
  _avg: StripeEventAvgAggregateOutputType | null
  _sum: StripeEventSumAggregateOutputType | null
  _min: StripeEventMinAggregateOutputType | null
  _max: StripeEventMaxAggregateOutputType | null
}

export type GetStripeEventGroupByPayload<T extends StripeEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StripeEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StripeEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StripeEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StripeEventGroupByOutputType[P]>
      }
    >
  >



export type StripeEventWhereInput = {
  AND?: Prisma.StripeEventWhereInput | Prisma.StripeEventWhereInput[]
  OR?: Prisma.StripeEventWhereInput[]
  NOT?: Prisma.StripeEventWhereInput | Prisma.StripeEventWhereInput[]
  id?: Prisma.StringFilter<"StripeEvent"> | string
  api_version?: Prisma.StringNullableFilter<"StripeEvent"> | string | null
  data?: Prisma.JsonFilter<"StripeEvent">
  request?: Prisma.JsonNullableFilter<"StripeEvent">
  type?: Prisma.StringFilter<"StripeEvent"> | string
  object?: Prisma.StringFilter<"StripeEvent"> | string
  account?: Prisma.StringNullableFilter<"StripeEvent"> | string | null
  created?: Prisma.DateTimeFilter<"StripeEvent"> | Date | string
  livemode?: Prisma.BoolFilter<"StripeEvent"> | boolean
  pending_webhooks?: Prisma.IntFilter<"StripeEvent"> | number
}

export type StripeEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  api_version?: Prisma.SortOrderInput | Prisma.SortOrder
  data?: Prisma.SortOrder
  request?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  object?: Prisma.SortOrder
  account?: Prisma.SortOrderInput | Prisma.SortOrder
  created?: Prisma.SortOrder
  livemode?: Prisma.SortOrder
  pending_webhooks?: Prisma.SortOrder
}

export type StripeEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StripeEventWhereInput | Prisma.StripeEventWhereInput[]
  OR?: Prisma.StripeEventWhereInput[]
  NOT?: Prisma.StripeEventWhereInput | Prisma.StripeEventWhereInput[]
  api_version?: Prisma.StringNullableFilter<"StripeEvent"> | string | null
  data?: Prisma.JsonFilter<"StripeEvent">
  request?: Prisma.JsonNullableFilter<"StripeEvent">
  type?: Prisma.StringFilter<"StripeEvent"> | string
  object?: Prisma.StringFilter<"StripeEvent"> | string
  account?: Prisma.StringNullableFilter<"StripeEvent"> | string | null
  created?: Prisma.DateTimeFilter<"StripeEvent"> | Date | string
  livemode?: Prisma.BoolFilter<"StripeEvent"> | boolean
  pending_webhooks?: Prisma.IntFilter<"StripeEvent"> | number
}, "id" | "id">

export type StripeEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  api_version?: Prisma.SortOrderInput | Prisma.SortOrder
  data?: Prisma.SortOrder
  request?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  object?: Prisma.SortOrder
  account?: Prisma.SortOrderInput | Prisma.SortOrder
  created?: Prisma.SortOrder
  livemode?: Prisma.SortOrder
  pending_webhooks?: Prisma.SortOrder
  _count?: Prisma.StripeEventCountOrderByAggregateInput
  _avg?: Prisma.StripeEventAvgOrderByAggregateInput
  _max?: Prisma.StripeEventMaxOrderByAggregateInput
  _min?: Prisma.StripeEventMinOrderByAggregateInput
  _sum?: Prisma.StripeEventSumOrderByAggregateInput
}

export type StripeEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.StripeEventScalarWhereWithAggregatesInput | Prisma.StripeEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.StripeEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StripeEventScalarWhereWithAggregatesInput | Prisma.StripeEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StripeEvent"> | string
  api_version?: Prisma.StringNullableWithAggregatesFilter<"StripeEvent"> | string | null
  data?: Prisma.JsonWithAggregatesFilter<"StripeEvent">
  request?: Prisma.JsonNullableWithAggregatesFilter<"StripeEvent">
  type?: Prisma.StringWithAggregatesFilter<"StripeEvent"> | string
  object?: Prisma.StringWithAggregatesFilter<"StripeEvent"> | string
  account?: Prisma.StringNullableWithAggregatesFilter<"StripeEvent"> | string | null
  created?: Prisma.DateTimeWithAggregatesFilter<"StripeEvent"> | Date | string
  livemode?: Prisma.BoolWithAggregatesFilter<"StripeEvent"> | boolean
  pending_webhooks?: Prisma.IntWithAggregatesFilter<"StripeEvent"> | number
}

export type StripeEventCreateInput = {
  id: string
  api_version?: string | null
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type: string
  object: string
  account?: string | null
  created: Date | string
  livemode: boolean
  pending_webhooks: number
}

export type StripeEventUncheckedCreateInput = {
  id: string
  api_version?: string | null
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type: string
  object: string
  account?: string | null
  created: Date | string
  livemode: boolean
  pending_webhooks: number
}

export type StripeEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  api_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type?: Prisma.StringFieldUpdateOperationsInput | string
  object?: Prisma.StringFieldUpdateOperationsInput | string
  account?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  livemode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pending_webhooks?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StripeEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  api_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type?: Prisma.StringFieldUpdateOperationsInput | string
  object?: Prisma.StringFieldUpdateOperationsInput | string
  account?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  livemode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pending_webhooks?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StripeEventCreateManyInput = {
  id: string
  api_version?: string | null
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type: string
  object: string
  account?: string | null
  created: Date | string
  livemode: boolean
  pending_webhooks: number
}

export type StripeEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  api_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type?: Prisma.StringFieldUpdateOperationsInput | string
  object?: Prisma.StringFieldUpdateOperationsInput | string
  account?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  livemode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pending_webhooks?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StripeEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  api_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  request?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  type?: Prisma.StringFieldUpdateOperationsInput | string
  object?: Prisma.StringFieldUpdateOperationsInput | string
  account?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  livemode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pending_webhooks?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StripeEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  api_version?: Prisma.SortOrder
  data?: Prisma.SortOrder
  request?: Prisma.SortOrder
  type?: Prisma.SortOrder
  object?: Prisma.SortOrder
  account?: Prisma.SortOrder
  created?: Prisma.SortOrder
  livemode?: Prisma.SortOrder
  pending_webhooks?: Prisma.SortOrder
}

export type StripeEventAvgOrderByAggregateInput = {
  pending_webhooks?: Prisma.SortOrder
}

export type StripeEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  api_version?: Prisma.SortOrder
  type?: Prisma.SortOrder
  object?: Prisma.SortOrder
  account?: Prisma.SortOrder
  created?: Prisma.SortOrder
  livemode?: Prisma.SortOrder
  pending_webhooks?: Prisma.SortOrder
}

export type StripeEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  api_version?: Prisma.SortOrder
  type?: Prisma.SortOrder
  object?: Prisma.SortOrder
  account?: Prisma.SortOrder
  created?: Prisma.SortOrder
  livemode?: Prisma.SortOrder
  pending_webhooks?: Prisma.SortOrder
}

export type StripeEventSumOrderByAggregateInput = {
  pending_webhooks?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type StripeEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  api_version?: boolean
  data?: boolean
  request?: boolean
  type?: boolean
  object?: boolean
  account?: boolean
  created?: boolean
  livemode?: boolean
  pending_webhooks?: boolean
}, ExtArgs["result"]["stripeEvent"]>

export type StripeEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  api_version?: boolean
  data?: boolean
  request?: boolean
  type?: boolean
  object?: boolean
  account?: boolean
  created?: boolean
  livemode?: boolean
  pending_webhooks?: boolean
}, ExtArgs["result"]["stripeEvent"]>

export type StripeEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  api_version?: boolean
  data?: boolean
  request?: boolean
  type?: boolean
  object?: boolean
  account?: boolean
  created?: boolean
  livemode?: boolean
  pending_webhooks?: boolean
}, ExtArgs["result"]["stripeEvent"]>

export type StripeEventSelectScalar = {
  id?: boolean
  api_version?: boolean
  data?: boolean
  request?: boolean
  type?: boolean
  object?: boolean
  account?: boolean
  created?: boolean
  livemode?: boolean
  pending_webhooks?: boolean
}

export type StripeEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "api_version" | "data" | "request" | "type" | "object" | "account" | "created" | "livemode" | "pending_webhooks", ExtArgs["result"]["stripeEvent"]>

export type $StripeEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StripeEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    api_version: string | null
    data: runtime.JsonValue
    request: runtime.JsonValue | null
    type: string
    object: string
    account: string | null
    created: Date
    livemode: boolean
    pending_webhooks: number
  }, ExtArgs["result"]["stripeEvent"]>
  composites: {}
}

export type StripeEventGetPayload<S extends boolean | null | undefined | StripeEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StripeEventPayload, S>

export type StripeEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StripeEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StripeEventCountAggregateInputType | true
  }

export interface StripeEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StripeEvent'], meta: { name: 'StripeEvent' } }
  /**
   * Find zero or one StripeEvent that matches the filter.
   * @param {StripeEventFindUniqueArgs} args - Arguments to find a StripeEvent
   * @example
   * // Get one StripeEvent
   * const stripeEvent = await prisma.stripeEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StripeEventFindUniqueArgs>(args: Prisma.SelectSubset<T, StripeEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StripeEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StripeEventFindUniqueOrThrowArgs} args - Arguments to find a StripeEvent
   * @example
   * // Get one StripeEvent
   * const stripeEvent = await prisma.stripeEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StripeEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StripeEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StripeEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventFindFirstArgs} args - Arguments to find a StripeEvent
   * @example
   * // Get one StripeEvent
   * const stripeEvent = await prisma.stripeEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StripeEventFindFirstArgs>(args?: Prisma.SelectSubset<T, StripeEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StripeEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventFindFirstOrThrowArgs} args - Arguments to find a StripeEvent
   * @example
   * // Get one StripeEvent
   * const stripeEvent = await prisma.stripeEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StripeEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StripeEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StripeEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StripeEvents
   * const stripeEvents = await prisma.stripeEvent.findMany()
   * 
   * // Get first 10 StripeEvents
   * const stripeEvents = await prisma.stripeEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stripeEventWithIdOnly = await prisma.stripeEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StripeEventFindManyArgs>(args?: Prisma.SelectSubset<T, StripeEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StripeEvent.
   * @param {StripeEventCreateArgs} args - Arguments to create a StripeEvent.
   * @example
   * // Create one StripeEvent
   * const StripeEvent = await prisma.stripeEvent.create({
   *   data: {
   *     // ... data to create a StripeEvent
   *   }
   * })
   * 
   */
  create<T extends StripeEventCreateArgs>(args: Prisma.SelectSubset<T, StripeEventCreateArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StripeEvents.
   * @param {StripeEventCreateManyArgs} args - Arguments to create many StripeEvents.
   * @example
   * // Create many StripeEvents
   * const stripeEvent = await prisma.stripeEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StripeEventCreateManyArgs>(args?: Prisma.SelectSubset<T, StripeEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StripeEvents and returns the data saved in the database.
   * @param {StripeEventCreateManyAndReturnArgs} args - Arguments to create many StripeEvents.
   * @example
   * // Create many StripeEvents
   * const stripeEvent = await prisma.stripeEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StripeEvents and only return the `id`
   * const stripeEventWithIdOnly = await prisma.stripeEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StripeEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StripeEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StripeEvent.
   * @param {StripeEventDeleteArgs} args - Arguments to delete one StripeEvent.
   * @example
   * // Delete one StripeEvent
   * const StripeEvent = await prisma.stripeEvent.delete({
   *   where: {
   *     // ... filter to delete one StripeEvent
   *   }
   * })
   * 
   */
  delete<T extends StripeEventDeleteArgs>(args: Prisma.SelectSubset<T, StripeEventDeleteArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StripeEvent.
   * @param {StripeEventUpdateArgs} args - Arguments to update one StripeEvent.
   * @example
   * // Update one StripeEvent
   * const stripeEvent = await prisma.stripeEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StripeEventUpdateArgs>(args: Prisma.SelectSubset<T, StripeEventUpdateArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StripeEvents.
   * @param {StripeEventDeleteManyArgs} args - Arguments to filter StripeEvents to delete.
   * @example
   * // Delete a few StripeEvents
   * const { count } = await prisma.stripeEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StripeEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, StripeEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StripeEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StripeEvents
   * const stripeEvent = await prisma.stripeEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StripeEventUpdateManyArgs>(args: Prisma.SelectSubset<T, StripeEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StripeEvents and returns the data updated in the database.
   * @param {StripeEventUpdateManyAndReturnArgs} args - Arguments to update many StripeEvents.
   * @example
   * // Update many StripeEvents
   * const stripeEvent = await prisma.stripeEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StripeEvents and only return the `id`
   * const stripeEventWithIdOnly = await prisma.stripeEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StripeEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StripeEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StripeEvent.
   * @param {StripeEventUpsertArgs} args - Arguments to update or create a StripeEvent.
   * @example
   * // Update or create a StripeEvent
   * const stripeEvent = await prisma.stripeEvent.upsert({
   *   create: {
   *     // ... data to create a StripeEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StripeEvent we want to update
   *   }
   * })
   */
  upsert<T extends StripeEventUpsertArgs>(args: Prisma.SelectSubset<T, StripeEventUpsertArgs<ExtArgs>>): Prisma.Prisma__StripeEventClient<runtime.Types.Result.GetResult<Prisma.$StripeEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StripeEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventCountArgs} args - Arguments to filter StripeEvents to count.
   * @example
   * // Count the number of StripeEvents
   * const count = await prisma.stripeEvent.count({
   *   where: {
   *     // ... the filter for the StripeEvents we want to count
   *   }
   * })
  **/
  count<T extends StripeEventCountArgs>(
    args?: Prisma.Subset<T, StripeEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StripeEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StripeEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StripeEventAggregateArgs>(args: Prisma.Subset<T, StripeEventAggregateArgs>): Prisma.PrismaPromise<GetStripeEventAggregateType<T>>

  /**
   * Group by StripeEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StripeEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StripeEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StripeEventGroupByArgs['orderBy'] }
      : { orderBy?: StripeEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StripeEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStripeEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StripeEvent model
 */
readonly fields: StripeEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StripeEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StripeEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StripeEvent model
 */
export interface StripeEventFieldRefs {
  readonly id: Prisma.FieldRef<"StripeEvent", 'String'>
  readonly api_version: Prisma.FieldRef<"StripeEvent", 'String'>
  readonly data: Prisma.FieldRef<"StripeEvent", 'Json'>
  readonly request: Prisma.FieldRef<"StripeEvent", 'Json'>
  readonly type: Prisma.FieldRef<"StripeEvent", 'String'>
  readonly object: Prisma.FieldRef<"StripeEvent", 'String'>
  readonly account: Prisma.FieldRef<"StripeEvent", 'String'>
  readonly created: Prisma.FieldRef<"StripeEvent", 'DateTime'>
  readonly livemode: Prisma.FieldRef<"StripeEvent", 'Boolean'>
  readonly pending_webhooks: Prisma.FieldRef<"StripeEvent", 'Int'>
}
    

// Custom InputTypes
/**
 * StripeEvent findUnique
 */
export type StripeEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * Filter, which StripeEvent to fetch.
   */
  where: Prisma.StripeEventWhereUniqueInput
}

/**
 * StripeEvent findUniqueOrThrow
 */
export type StripeEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * Filter, which StripeEvent to fetch.
   */
  where: Prisma.StripeEventWhereUniqueInput
}

/**
 * StripeEvent findFirst
 */
export type StripeEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * Filter, which StripeEvent to fetch.
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StripeEvents to fetch.
   */
  orderBy?: Prisma.StripeEventOrderByWithRelationInput | Prisma.StripeEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StripeEvents.
   */
  cursor?: Prisma.StripeEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StripeEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StripeEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StripeEvents.
   */
  distinct?: Prisma.StripeEventScalarFieldEnum | Prisma.StripeEventScalarFieldEnum[]
}

/**
 * StripeEvent findFirstOrThrow
 */
export type StripeEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * Filter, which StripeEvent to fetch.
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StripeEvents to fetch.
   */
  orderBy?: Prisma.StripeEventOrderByWithRelationInput | Prisma.StripeEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StripeEvents.
   */
  cursor?: Prisma.StripeEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StripeEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StripeEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StripeEvents.
   */
  distinct?: Prisma.StripeEventScalarFieldEnum | Prisma.StripeEventScalarFieldEnum[]
}

/**
 * StripeEvent findMany
 */
export type StripeEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * Filter, which StripeEvents to fetch.
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StripeEvents to fetch.
   */
  orderBy?: Prisma.StripeEventOrderByWithRelationInput | Prisma.StripeEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StripeEvents.
   */
  cursor?: Prisma.StripeEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StripeEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StripeEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StripeEvents.
   */
  distinct?: Prisma.StripeEventScalarFieldEnum | Prisma.StripeEventScalarFieldEnum[]
}

/**
 * StripeEvent create
 */
export type StripeEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * The data needed to create a StripeEvent.
   */
  data: Prisma.XOR<Prisma.StripeEventCreateInput, Prisma.StripeEventUncheckedCreateInput>
}

/**
 * StripeEvent createMany
 */
export type StripeEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StripeEvents.
   */
  data: Prisma.StripeEventCreateManyInput | Prisma.StripeEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StripeEvent createManyAndReturn
 */
export type StripeEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * The data used to create many StripeEvents.
   */
  data: Prisma.StripeEventCreateManyInput | Prisma.StripeEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StripeEvent update
 */
export type StripeEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * The data needed to update a StripeEvent.
   */
  data: Prisma.XOR<Prisma.StripeEventUpdateInput, Prisma.StripeEventUncheckedUpdateInput>
  /**
   * Choose, which StripeEvent to update.
   */
  where: Prisma.StripeEventWhereUniqueInput
}

/**
 * StripeEvent updateMany
 */
export type StripeEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StripeEvents.
   */
  data: Prisma.XOR<Prisma.StripeEventUpdateManyMutationInput, Prisma.StripeEventUncheckedUpdateManyInput>
  /**
   * Filter which StripeEvents to update
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * Limit how many StripeEvents to update.
   */
  limit?: number
}

/**
 * StripeEvent updateManyAndReturn
 */
export type StripeEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * The data used to update StripeEvents.
   */
  data: Prisma.XOR<Prisma.StripeEventUpdateManyMutationInput, Prisma.StripeEventUncheckedUpdateManyInput>
  /**
   * Filter which StripeEvents to update
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * Limit how many StripeEvents to update.
   */
  limit?: number
}

/**
 * StripeEvent upsert
 */
export type StripeEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * The filter to search for the StripeEvent to update in case it exists.
   */
  where: Prisma.StripeEventWhereUniqueInput
  /**
   * In case the StripeEvent found by the `where` argument doesn't exist, create a new StripeEvent with this data.
   */
  create: Prisma.XOR<Prisma.StripeEventCreateInput, Prisma.StripeEventUncheckedCreateInput>
  /**
   * In case the StripeEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StripeEventUpdateInput, Prisma.StripeEventUncheckedUpdateInput>
}

/**
 * StripeEvent delete
 */
export type StripeEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
  /**
   * Filter which StripeEvent to delete.
   */
  where: Prisma.StripeEventWhereUniqueInput
}

/**
 * StripeEvent deleteMany
 */
export type StripeEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StripeEvents to delete
   */
  where?: Prisma.StripeEventWhereInput
  /**
   * Limit how many StripeEvents to delete.
   */
  limit?: number
}

/**
 * StripeEvent without action
 */
export type StripeEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StripeEvent
   */
  select?: Prisma.StripeEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StripeEvent
   */
  omit?: Prisma.StripeEventOmit<ExtArgs> | null
}
